### ISSUE TITLE
cookiecutter.repo_name is hardcoded as app root

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#10]
This caused some problems with cookiecutter-dj-package. Please do one of the following:

- Document that there needs to be a top level `{{cookiecutter.repo_name}}` directory.
- Remove the hard-coded behavior of cookiecutter.repo_name.

**Comment by mbra** [comment]
:+1:

**Comment by pydanny** [comment]
Fixed long ago.
