### ISSUE TITLE
cookiecutter cannot create a project tree using a bash script

### ISSUE THREAD

**Issue by edesz** [audreyr/cookiecutter#1010]
* Cookiecutter version: 1.6.0
* Template project url: N/A
* Python version: 2.7.14
* Operating System: Ubuntu 17.10

### Description:

**What am I trying to get done?**
I am trying to create a cookiecutter project using a `bash` script on Ubuntu 17.10. I am following the beginner's guide [here](http://cookiecutter.readthedocs.io/en/latest/first_steps.html) to create this project.

**What went wrong?**
In the beginner's project, some commands are run from the CLI.
example. `mkdir {{cookiecutter.directory_name}}`. What I need to do is to place these commands into a bash script and the commands will be run when the bash script is executed. I put these same _commands_ into a bash script and made the script executable. When `cookiecutter` runs, it does not execute the script. Instead, it creates a folder with the same name as the bash script.

### What I've run:

Here is my setup:

```
username@user-PC:~$ mkdir ~/cookietests
username@user-PC:~$ cd cookietests
username@user-PC:~/cookietests$ virtualenv .venv
username@user-PC:~/cookietests$ source .venv/bin/activate
(.venv) username@user-PC:~/cookietests/cookietests$ pip install cookiecutter
(.venv) username@user-PC:~/cookietests/cookietests$ mkdir HelloCookieCutter1

```
Here is `cookiecutter.json`:

```
{
    "script_name": "mytest"
    "directory_name": "Hello",
    "file_name": "Howdy",
    "greeting_recipient": "Julie"
}
```

Here is my full `{{cookiecutter.script_name}}.sh` - these are the _commands_ I was referring to earlier:

```
mkdir '{{cookiecutter.directory_name}}'
cd '{{cookiecutter.directory_name}}'
touch '{{cookiecutter.file_name}}'.py
echo "print("Hello, '{{cookiecutter.greeting_receipient}}'!")" >> {{cookiecutter.file_name}}.py
```

Here is the directory tree:

```
(.venv) username@user-PC:~$ cd ~/cookietests
(.venv) username@user-PC:~/cookietests$ tree
.
└── HelloCookieCutter1
    ├── cookiecutter.json
    ├── {{cookiecutter.script_name}}.sh
    └── mytest.sh

2 directories, 2 files
```

Now, I run `cookiecutter` but I get an error message:

```
(.venv) username@user-PC:~/cookietests$ cd cookietests/HelloCookieCutter1
(.venv) username@user-PC:~/cookietests$ chmod u+x {{cookiecutter.script_name}}.sh
(.venv) username@user-PC:~/cookietests/HelloCookieCutter1$ cookiecutter HelloWorld1

Traceback (most recent call last):
  File "/home/username/cookietests/.venv/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/click/core.py", 
    line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/click/core.py"
    line 697, in main
    rv = self.invoke(ctx)
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/click/core.py",
   line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/click/core.py",
   line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/cookiecutter/cli.py",
line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/cookiecutter/main.py",
line 94, in cookiecutter
    output_dir=output_dir
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/cookiecutter/generate.py",
line 301, in generate_files
    with work_in(template_dir):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/username/cookietests/.venv/local/lib/python2.7/site-packages/cookiecutter/utils.py",
line 71, in work_in os.chdir(dirname)
OSError: [Errno 20] Not a directory: '/home/username/cookietests/HelloCookieCutter1
    /{{cookiecutter.script_name}}.sh'
```

It has created a new file at `/home/username/cookietests/HelloCookieCutter1/mytest.sh'`

Does `cookiecutter` allow bash scripts to create a project's directory tree? Is there a way to instruct cookiecutter to execute `./mytest.sh`?

**Comment by luzfcb** [comment]
probably, you should send the link from a public repository, which contains your cookiecutter template

**Comment by hackebrot** [comment]
Hi @edesz! 👋 

Cookiecutter requires a templated directory at the top level of your template project.

```text
HelloCookiecutter/
├── cookiecutter.json
└── {{cookiecutter.project_name}}
    ├── mytest.sh
    └── {{cookiecutter.script_name}}.py
```

As for running bash scripts check out the documentation on [post generation hooks](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html).

Cookiecutter generates new projects based on an existing directory tree of a template. So typically you do not need to create directories in bash script. It is quite common however for more complex template projects to use bash or Python scripts to prune optional files etc.

Hope this helps! 🍪

**Comment by edesz** [comment]
@hackebrot Thanks! Your comment helped. I previously had mis-understood. Now it is much clearer.
