### ISSUE TITLE
Trouble deploying Extra context example using the Advanced Usage docs

### ISSUE THREAD

**Issue by edesz** [audreyr/cookiecutter#1012]
I am having difficulty running  the **Advanced example Defaults + Extra Context**, using the [docs](http://cookiecutter.readthedocs.io/en/latest/advanced/suppressing_prompts.html#advanced-example-defaults-extra-context).

I have created a minimal reproducible example using [this project](http://cookiecutter.readthedocs.io/en/latest/first_steps.html#learn-the-basics-of-cookiecutter-by-creating-a-cookiecutter).

```
$ mkdir cookiecutter-fabric-esneor
$ cd cookiecutter-fabric-esneor
$ mkdir {{cookiecutter.directory_name}}
$ cd {{cookiecutter.directory_name}}
```

Here is my `cookiecutter.json`:

```
    {
    "fabric_type": "Vbox",
    "username": "Tom Smith",
    "user": "{{cookiecutter.username.lower().replace(' ','')}}",
    "timestamp": "{{cookiecutter.timestamp}}"
    }
```

Here is my `cookiecutter_runner.py` (based on [this](https://github.com/audreyr/cookiecutter/blob/b2f7ab5041919b27411a278547916424168a0250/docs/advanced/injecting_context.rst)):

```
from cookiecutter.main import cookiecutter

from datetime import datetime

cookiecutter(
    'Hello',
    extra_context={'timestamp': datetime.utcnow().isoformat()}
)
```

My tree is (based on [this layout](http://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html#using-pre-post-generate-hooks-0-7-0)):

```
$ cd ~
$ tree
cookiecutter-fabric-esneor/
├── {{cookiecutter.directory_name}}/
    └── {{cookiecutter.directory_name}}.sh
└── cookiecutter.json
└── cookiecutter_runner.py
```

This is the contents of `{{cookiecutter.directory_name}}.sh`:

```
#!/bin/bash
echo "{{cookiecutter.timestamp}}"
```
When I run

```
$ cd ~
$ cookiecutter cookiecutter-fabric-esneor
```

I get this:

```
fabric_type [Vbox]:
username [Tom Smith]:
user [tomsmith]:
directory_name [fab_dir]:
Unable to render variable 'timestamp'
Error message: 'dict object' has no attribute 'timestamp'
Context: {
    "cookiecuttter": {
    .
    .
    .
    "timestamp": "{{cookiecutter.timestamp}}"
    }
}
```

It's a pretty basic project and I've followed the documentation instructions but it seems like something is missing in the `{{cookiecutter.directory_name}}` directory.

Is there another page in the documentation that has a full example of how to use the Extra Context?

* Cookiecutter version: 1.6.0
* Python version: 2.7.14
* Operating System: Ubuntu 17.10

EDIT: I hope you don't mind me adding the 2 proposed labels to the title. I thought it would be helpful when reading this post.

`cookiecutter.json` is missing: `"directory_name": "fab_dir"`

**Comment by hackebrot** [comment]
Hi @edesz! 👋 

This looks to me like there is a problem with your ``cookiecutter.json`` file:

```json
{
  "fabric_type": "Vbox",
  "username": "Tom Smith",
  "user": "{{cookiecutter.username.lower().replace(' ','')}}",
  "timestamp": "{{cookiecutter.timestamp}}"
}
```

When cookiecutter prompts the user for input on the CLI, it attempts to update default values based on the provided template for each variable. For example if the user specifies ``username`` to be ``"Audrey Roy Greenfeld"`` the default value for ``user`` will be rendered as ``"audreyroygreenfeld"``. This functionality happens regardless of whether you provide extra context or not.

In this particular case you instruct cookiecutter to update the default value for the ``timestamp`` variable to the value of ``timestamp`` itself, which doesn't work. So if you change the default value for timestamp to something else which doesn't reference the variable itself, you shouldn't see above error.

```json
{
  "fabric_type": "Vbox",
  "username": "Tom Smith",
  "user": "{{cookiecutter.username.lower().replace(' ','')}}",
  "timestamp": ""
}
```

Thank you for providing a detailed description for this problem. 🙇 

Hope this helps and isn't too confusing (It's late here in Berlin/Germany 😴 )

**Comment by hackebrot** [comment]
Based on the information that you provided ``cookiecutter_runner.py`` will not be executed when running cookiecutter. What you want to do is run the script directly rather than calling ``cookiecutter`` directly from the CLI and update the template argument accordingly. 

```python
from datetime import datetime

from cookiecutter.main import cookiecutter

def run():
    template = os.path.dirname(os.path.realpath(__file__))

    cookiecutter(
        template,
        extra_context={
            'timestamp': datetime.utcnow().isoformat(),
        },
    )


if __name__ == '__main__':
    run()
```

```bash
$ python cookiecutter-fabric-esneor/cookiecutter_runner.py
```

**Comment by edesz** [comment]
Done!

Rafael, your 2nd post answered the next question I was about to ask. Thanks so much!

However, I am not sure what you meant by "update the template argument".....I simply used the same as you did and made no changes. It worked for me. I did not make any updates at all. All I had to change was to add one line at the top: `import os`....everything else in my `*.py` file was identical to what you posted.

**Comment by edesz** [comment]
If a dictionary variable should be set to a default value, like this python file:

```
cookiecutter(
        template,
        extra_context={
            'timestamp': datetime.utcnow().isoformat(),
            "image_type": {
                   "name": "Bitmap", "library": "libbmp", "apps": ["Paint", "GIMP"]}
                   }
        )
```

with this `json` file

```
{
  "fabric_type": "Vbox",
  "username": "Tom Smith",
  "user": "{{cookiecutter.username.lower().replace(' ','')}}",
  "timestamp": "",
  "image_type": ""
}
```
I got an error message:

$ python cookiecutter-fabric-esneor/cookiecutter_runner.py

did not work. It gave
```
image_type []:
Error message: 'dict object' has no attribute 'image_type'
```
Does **extra context** support dictionary variables?

**Comment by Kludex** [comment]
This was treated as "wrong approach", but what if this was actually a feature request? Run a default python file using `cookiecutter <repository_name>` is something interesting.

Should I open a new issue? Would this even be considered?

**Comment by edesz** [comment]
Sorry for the late reply......this issue was based on an advanced example from the docs. So, I think that it might not be very useful for most uses of `cookiecutter`. Also, there is a new context format in development (see [#1566](https://github.com/cookiecutter/cookiecutter/pull/1566)) - it may be a good idea to wait until that is implemented and see if that helps with your workflow (maybe you don't need to use the approach from this issue when the new format takes effect).
