### ISSUE TITLE
Python 3.3 support

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#1017]
Hey there! 👋 

I just pinned our test dependencies to use ``pytest<3.3.0`` via 0c92f3c893f558d3d5a4f8cb5bf5a3cfb894261d as the [latest pytest release][pytest release] dropped support for Python 3.3.

How do you feel about Python 3.3 support in Cookiecutter?

@audreyr @pydanny @michaeljoseph @pfmoore 

[pytest release]: https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-0-2017-11-23

**Comment by hugovk** [comment]
I would suggest that new projects only support non-EOL versions of Python which are supported by the core team and still receive security updates.

![image](https://user-images.githubusercontent.com/1324225/33606274-9c289a04-d9c5-11e7-91a8-5b02d4e2d3a0.png)

https://en.wikipedia.org/wiki/CPython#Version_history

Many important Python libraries (eg. testing, distribution) are dropping support for EOL Python 2.6 and 3.3, making pinning and ugly workarounds necessary to maintain support for those old ones.

I don't think fresh, new projects should be given that burden.

Furthermore, 3.3 has very little use in general. Here's the pip installs from PyPI for the last month (via `pypinfo --percent --pip "" pyversion`).

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   78.0% |    454,240,817 |
| 3.6            |    8.6% |     50,301,669 |
| 3.5            |    8.3% |     48,225,874 |
| 3.4            |    3.8% |     22,052,677 |
| 2.6            |    1.1% |      6,341,968 |
| 3.3            |    0.1% |        610,051 |
| 3.7            |    0.1% |        460,986 |
| 3.2            |    0.0% |         44,590 |
| None           |    0.0% |         23,421 |
| 3.1            |    0.0% |             39 |
| 2.8            |    0.0% |             32 |

**Comment by pydanny** [comment]
I like the idea of dropping Python 3.3 support. Although it makes me sad because that's the version this project started on. 😭

**Comment by hugovk** [comment]
Onwards and upwards!

**Comment by pydanny** [comment]
@hackbrot, I was going to work on this ticket. You okay with that?

**Comment by hackebrot** [comment]
Sure thing! Go for it, @pydanny 👨‍💻 🚀

**Comment by hackebrot** [comment]
Did you see #1024, @pydanny?
