### ISSUE TITLE
Choice Variables remove spaces/newlines

### ISSUE THREAD

**Issue by thornycrackers** [audreyr/cookiecutter#1031]
* Cookiecutter version: 1.3.0 - 1.6.0
* Template project url: https://github.com/thornycrackers/cookiecutter-newline
* Python version: 3.6.2
* Operating System: mac/Arch linux

### Description:

I'm trying to write a cookie cutter and use the choices to render conditional content. My issue is that when cookie cutter renders the project it is removing all of the white space and I the final version ends up ending up on the same line.

```
This is my text.

{%- if cookiecutter.project_type == "option1" -%}

option 1

{%- else -%}

option 2

{%- endif -%}
```

but whenever I run cookiecutter I end up getting

```
This is my text.option 1
```

I couldn't find anything in the docs about this, it's possible I missed it, but is this the intended behavior?

**Comment by thornycrackers** [comment]
I didn't realize that the `{%-` controlled whitespace I just thought that's how you write the templates.

http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

**Comment by vinzeebreak** [comment]
Link is broken, here is a link to a similar resource: https://ttl255.com/jinja2-tutorial-part-3-whitespace-control/
