### ISSUE TITLE
npm and ipython widgets

### ISSUE THREAD

**Issue by achapkowski** [audreyr/cookiecutter#1035]
* Cookiecutter version: 1.6.0
* Template project url: https://github.com/jupyter/widget-cookiecutter.git
* Python version: 3.6
* Operating System: Windows

### Description:

Hello,

I just have a question: I want to build an ipython widget, but I don't want to create an account on NPM, can I just host the stuff locally still I'm ready to push everything out to the world?  Also, NPM takes forever to package, what is the best way to speed up using node build?

**Comment by luzfcb** [comment]
@achapkowski your question is not related to this project. this repository deals with things related to the development of the cookiecutter itself and not of projects that use cookiecutter, like https://github.com/jupyter/widget-cookiecutter.git .

Please, send your question to `widget-cookiecutter` Gitter chat room: https://gitter.im/jupyter-widgets/Lobby

Thanks. :-)
