### ISSUE TITLE
ImportError raised when trying to load 'debug_toolbar.templatetags.compat': cannot import name 'url'

### ISSUE THREAD

**Issue by glxiong** [audreyr/cookiecutter#1053]
* Cookiecutter version: git
* Template project url:
* Python version: 3.5.3
* Operating System: Mac

After creating initial django cookiecutter code, I got the following error

InvalidTemplateLibrary
Invalid template library specified. ImportError raised when trying to load 'debug_toolbar.templatetags.compat': cannot import name 'url'
/Users/test/anaconda/lib/python3.5/site-packages/django/template/backends/django.py in get_package_libraries, line 125
/Users/test/anaconda/bin/python

IT seems that this line from the django-debug_toolbar has problem:
lib/python3.5/site-packages/debug_toolbar/templatetags/compat.py
from ..compat import url as url_compat

**Comment by luzfcb** [comment]
@glxiong this is not a Cookiecutter bug. it's probably a bug in the cookiecuter-based project template you're using.

**Comment by pydanny** [comment]
Closed as a bug in a Cookiecutter template, not an issue with Cookiecutter itself. Please file your pair with the template you were trying to use.
