### ISSUE TITLE
Improve user experience setting Pypi password for travis

### ISSUE THREAD

**Issue by rutgerhofste** [audreyr/cookiecutter#1064]
* Cookiecutter version: 1.6.0
* Template project url: https://github.com/rutgerhofste/aqueduct3
* Python version: 3.5
* Operating System: Windows 10 64 bit

### Description:

Add encrypted pypi password to travis.yaml file. The suggested command  (`travis encrypt --add deploy.password`) in the docs has a poor user experience and caused problems on Windows. Suggested improved user experience by switching to:
`travis encrypt SOMEVAR="REPLACE WITH PYPI PASSWORD" --add deploy.password`

[docs](https://docs.travis-ci.com/user/encryption-keys/)

### What I've run:

```
travis encrypt --add deploy.password
```

**Comment by luzfcb** [comment]
@rutgerhofste this is not a Cookiecutter problem.

It is probably a case that should be addressed in the issue tracker of the Cookiecutter Template you used to generate the project.

I think you should report this on https://github.com/audreyr/cookiecutter-pypackage

**Comment by rutgerhofste** [comment]
I createa a [PR](https://github.com/audreyr/cookiecutter-pypackage/pull/421). Closing this issue here.
