### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [audreyr/cookiecutter#1065]
Hello Sir. I'm a Graphics and UI/UX Designer. I want to offering a new logo for your apps as my open source contribution. If you don't mind, I will create for you and post my design proposal here.

**Comment by anharismail** [comment]
I will put a preview, after the repositories owner answer my offer. To make sure, this repositories still available

**Comment by pydanny** [comment]
Thank you for your offer but we are absolutely not interested in a new logo.

**Comment by anharismail** [comment]
Okay, no problem Sir.
