### ISSUE TITLE
actual DJANGO_SECRET_KEY put in env.example but env.example not in .gitgnore

### ISSUE THREAD

**Issue by netvigator** [audreyr/cookiecutter#1075]
* Cookiecutter version: 1.5.1
* Template project url:
* Python version: 3.4.3
* Operating System: ubuntu 16.04

### Description: actual DJANGO_SECRET_KEY put in  env.example but env.example not in .gitgnore
end result: my DJANGO_SECRET_KEY is in version control, there for the whole world to see!  Not secret!
My next step is to google 'get new DJANGO_SECRET_KEY'

// REPLACE ME: It is OK to put DJANGO_SECRET_KEY put in env.example but env.example should be included in .gitgnore.  Or omit DJANGO_SECRET_KEY from env.example.  Either is better.

### What I've run: n/a

```
// REPLACE ME: I found the mistake just now.
```

**Comment by pydanny** [comment]
This looks like an issue related to a specific Cookiecutter template and not Cookiecutter itself. Please report this issue on that, rather than Cookiecutter itself.
