### ISSUE TITLE
Multiple template directories

### ISSUE THREAD

**Issue by KyleXie** [audreyr/cookiecutter#1097]
* Cookiecutter version: 1.6
* Template project url:
* Python version: 3.6
* Operating System: macOS

### Description:

I would like to create a cookiecutter template with two directories, like {{cookiecutter.dir1}} and {{cookiecutter.dir2}}, but it only generate one directory, seems cookiecutter only try to find one directory and render it, after that it just ignore others.

So what I have to do if I want my template has more than one template directories on project root?

**Comment by hackebrot** [comment]
Hi @KyleXie! 👋 

Cookiecutter requires you to have one templated directory at the top level.

```text
{{cookiecutter.project_name}}/
├── {{cookiecutter.dir1}}
└── {{cookiecutter.dir2}}
```

You could however write a script on top of Cookiecutter's Python API to support multiple directories or  add a [post-generate hook][hooks] to move the generated directories to a different location.

[hooks]: https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html

Hope this helps!

**Comment by KyleXie** [comment]
Hi @hackebrot , thanks very much, use post-generate hook is a good idea for my situation.
