### ISSUE TITLE
Unknown placeholders are silently ignored (replaced with empty string)

### ISSUE THREAD

**Issue by jenisys** [audreyr/cookiecutter#111]
VERSION: cookiecutter-0.7.0

Unknown placeholders in dirname/filename or Jinja templates are silently ignored and replaced with empty string. This is BAD because neither the template provider nor the template user detects these problems easily.

```python
# FILE: cookiecutter/generate.py
# FUNCTION: generate_files()
    # -- CURRENTLY:
    env = Environment()
    # -- SHOULD-BE:
    env = Environment(undefined=StrictUndefined)
```

**Comment by pydanny** [comment]
Has this been resolved?

**Comment by ojongerius** [comment]
Hey there,

What we feel the right approach is? My PR merely added `undefined=StrictUndefined`, as @jenisys suggested. That works fine for our use case, as we prefer seeing as stack trace.

I'd really like to get a solution merged, it makes using of cookiecutter much less error prone.

@audreyr you write:
> I've been thinking about the user experience of this and agree. +1 on aborting if a var hasn't been set, and terminating with a helpful error message.

Where would you think we should do this? *main.py*? If we put generate_files() in a try, we can catch the UndefinedError and do something like sys.exit. Something like so:

```sh
diff --git a/cookiecutter/main.py b/cookiecutter/main.py
index a5cde54..8c80849 100755
--- a/cookiecutter/main.py
+++ b/cookiecutter/main.py
@@ -14,12 +14,15 @@ library rather than a script.
 from __future__ import unicode_literals
 import logging
 import os
+import sys

 from .config import get_user_config
 from .prompt import prompt_for_config
 from .generate import generate_context, generate_files
 from .vcs import clone

+from jinja2.exceptions import UndefinedError
+
 logger = logging.getLogger(__name__)

 builtin_abbreviations = {
@@ -97,7 +100,11 @@ def cookiecutter(template, checkout=None, no_input=False, extra_context=None):
     context['cookiecutter'] = prompt_for_config(context, no_input)

     # Create project from local context and project template.
-    generate_files(
-        repo_dir=repo_dir,
-        context=context
-    )
+    try:
+        generate_files(
+            repo_dir=repo_dir,
+            context=context
+        )
+    except UndefinedError as e:
+        print "An example of a friendly message to the user:", e
+        sys.exit(2)
diff --git a/tests/test_generate_files.py b/tests/test_generate_files.py
```

My other question is is about testing. The tests in test_generate_files.py fail, as the test repos trigger the exception. Getting the tests to pass would involve updating the test repos to the do not cause the failures. I'm happy to help out, but would like to agree on a strategy before I invest time.

@audreyr if you are wiling to help out with the testing: even better :smile:

**Comment by hackebrot** [comment]
Please review #598, thanks :bow:
