### ISSUE TITLE
Cookiecutter needs a "just copy this stuff" mode.

### ISSUE THREAD

**Issue by BillWhite** [audreyr/cookiecutter#133]
Cookiecutter is really helpful, and I'm grateful that you have done this work.  However, it needs some way to express that a folder is not a template.  It's just stuff to be copied to the output.

I'm working on something with which I want to distribute google mock.  But some of the gmock code looks like template code to jinjia.  I could find all of that stuff and escape it, but then I'd have to redo it for the next version of gmock, and I don't really think changing gmock is a good idea anyway.
 
Maybe there is some way to do this, but I haven't found it.

**Comment by lanshark** [comment]
+1

**Comment by hackebrot** [comment]
http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render :smile_cat:
