### ISSUE TITLE
Document the command line options

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter#166]
We need a page in the docs that describes what all the command line options for Cookiecutter are.

Maybe something along the lines of http://www.pip-installer.org/en/latest/reference/pip.html#general-options (note: that seems to be autogenerated somehow, but I'm not sure how)

**Comment by pydanny** [comment]
Does http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#command-line-options mean we can close this issue?

**Comment by maiksensi** [comment]
I think so :)

**Comment by hackebrot** [comment]
See ``cookiecutter/docs/ccext.py`` :+1:
