### ISSUE TITLE
Validating input using regexs

### ISSUE THREAD

**Issue by luismartingil** [audreyr/cookiecutter#175]
It would be cool to have regex validations for the inputs,

_cookiecutter.validation.json_

```
{
    "repo_name": "^[a-z]*$",
    "project_name": "^[A-Z]"
}
```

If invalid (whether is default value or input by the user) is found, raises Exception and exists the cookie cutter process.

**Comment by hackebrot** [comment]
Closing this in favor of #848, as it does support user inout validation based on types and regex patterns.

**Comment by bbodensieck** [comment]
In case someone is searching it
https://cookiecutter.readthedocs.io/en/1.7.0/advanced/hooks.html#example-validating-template-variables
