### ISSUE TITLE
A copy of the variables used should be optionally added to the top-level project directory

### ISSUE THREAD

**Issue by ryanolson** [audreyr/cookiecutter#188]
A copy of the actual values used should be optionally placed in the top-level directory created by cookiecutter.

Combined with Issue #187, this will allow one to easily re-initialize a project when the template changes.

```
cookiecutter --save-params cookiecutter-template
```

would generate a `cookiecutter.json` file in my project directory.

Then I could make changes to cookiecutter-template and reissue

```
cookiecutter --paramaters myproject/cookiecutter.json cookiecutter-tempate
```

This would overwrite the templated components of myproject using the same variables I had used prior, leaving any files that I added untouched.

**Comment by jhermann** [comment]
For a working process, even if it has some rough edges…

https://github.com/Springerle/py-generic-project#feature-toggles

**Comment by pydanny** [comment]
Ooooh! Nice @jhermann!

**Comment by jhermann** [comment]
Well, merge/review my open PRs, so I can stack some more on top. :wink:

**Comment by hackebrot** [comment]
I think ``--replay`` of #501 completes this story for the most part :triumph:
