### ISSUE TITLE
modernizr.js file raises jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag

### ISSUE THREAD

**Issue by oubiga** [audreyr/cookiecutter#189]
Hi!
I would like to add modernizr.js to my template, but when I run:
```$ cookiecutter https://github.com/oubiga/cc-dj-cms-heroku.git ```
I got:
```jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag```
due to:
```File "./static/js/vendor/modernizr.js", line 457
    injectElementWithStyles(['@media (',prefixes.join('touch-enabled),('),mod,')','{#modernizr{top:9px;position:absolute}}'].join(''), function( node ) {```

I'm not sure if there is some way to avoid this issue.

**Comment by hackebrot** [comment]
Can you possibly try to use [copy-without-render](http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render) for this file?

Closing this for now. We can open a Change Request for what @michaeljoseph mentioned though :bow:

**Comment by oubiga** [comment]
This works. Thank you, @hackebrot & @michaeljoseph

**Comment by hackebrot** [comment]
Great! Happy to hear that :smile_cat:
