### ISSUE TITLE
Make list of of third-party cookiecutter indexes and related tools

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#208]
There is a growing ecosystem of tools and indexes for the project. We need to make a list of all the tools that use the cookiecutter API, are indexes of cookiecutter project templates, or are cookiecutter-compatible.

**Comment by pydanny** [comment]
Should we just go with what we have on the README?

**Comment by michaeljoseph** [comment]
@pydanny yeah, that should be fine for the first iteration.

**Comment by hackebrot** [comment]
Looks like we already have this in place by now :smile:
