### ISSUE TITLE
Implement standards for projects listed in the README

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#216]
@audreyr used to manually check each `ccokiecutter` template before allowing it in master. Unfortunately, since she's delegated authority that's slipped. Tasks:

* Document how we test each `cookiecutter` before adding it to the README
* Test all listed `ccokiecutters`
* Test all future submissions of `cookiecutters`

**Comment by hackebrot** [comment]
We have no control over how template projects are managed. Even if we check the template up front, it's up to the author to change it afterwards (and possibly break our conventions) or abandon the template project altogether.

I added minimal docs in #431
