### ISSUE TITLE
Document how the sys.stdin is replaced for Windows tests

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#254]
In `tests/test_prompt.py`, this code allows us to bypass tests on Windows stopping on the Y/N prompt. This issue is for documenting why and how it works in Cookiecutter's code as well as the formal documentation.

```python
#tests/test_prompt.py
if 'windows' in platform.platform().lower():

    old_stdin = sys.stdin

    class X(object):
        def readline(self):
            return '\n'
    sys.stdin = X()
```

**Comment by hackebrot** [comment]
By using the **click** library, I think we don't have this problem any more.

Let me know if, I am missing something here.
