### ISSUE TITLE
100% Coverage

### ISSUE THREAD

**Issue by michaeljoseph** [audreyr/cookiecutter#261]
I want it.
Bad.

**Comment by hackebrot** [comment]
We are at 99.64% :joy_cat: 

The only statements missing are the ``rm -rf`` like remove callback, which is really awkward to test.

**Comment by hackebrot** [comment]
We made it 😂

Thanks @ewjoachim

**Comment by ewjoachim** [comment]
Nothing else to say but :cake: \o/
