### ISSUE TITLE
Take a lookup path from $COOKIEJARS

### ISSUE THREAD

**Issue by jhermann** [audreyr/cookiecutter#284]
I want to add a feature where if the env var COOKIEJARS exists (or possibly CC_COOKIEJARS, with less risk of any naming collisions), it's used to look for locally installed cookiecutters. Semantics should be like MANPATH, including that an empty path element represents the default location (i.e. `cookiecutters_dir`).

Use-case is to point to e.g. git submodule collections that are installed somewhere in the fielsystem and need to be found. Note that these dirs would be never modified by cookiecutter itself, unlike the `cookiecutters_dir` cache.

Thoughts?

**Comment by hackebrot** [comment]
With #825 you can now refer to local templates based on your ``cookiecutters_dir`` settings.
