### ISSUE TITLE
Cookiecutter moulds and documentation

### ISSUE THREAD

**Issue by michaeljoseph** [audreyr/cookiecutter#296]
Since all these documentation / template updates trail the recent changes in master, I'm tempted to cherrypick them into one PR?
#74 
#131 
#143 
#278 
#283 

cc: @audreyr @pydanny @pfmoore

**Comment by hackebrot** [comment]
I was thinking if we could possibly ask the template authors to define some kind of checklist when submitting a PR. Given such a checklist we can verify more easily that the cookiecutters are working as expected.

To be perfectly honest we cannot guarantee the quality of the templates as we do not maintain them. So it may work when we accept a PR but break at some point. :worried:

**Comment by hackebrot** [comment]
Closing this one as all of the linked PRs are closed by now! :smile:
