### ISSUE TITLE
Consider moving to six or future for Python 2/3 compatibility

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#301]
**Should we move to one of these libraries?** I think so, as it would mean we could nearly eliminate the `compat.py` module, improving test coverage.

**Which library?** `six`, `future`, or something else?

**Comment by pydanny** [comment]
We'll go with python-future!

**Comment by hackebrot** [comment]
PR #529 introduces **future** based on @michaeljoseph's work on #438
