### ISSUE TITLE
Add a webhook for Gitter

### ISSUE THREAD

**Issue by michaeljoseph** [audreyr/cookiecutter#313]
![screen shot 2014-11-09 at 12 08 28](https://cloud.githubusercontent.com/assets/169933/4967107/65a5bc10-67f8-11e4-8561-e7c2c9f1facb.png)

**Comment by pydanny** [comment]
I think a very slow moving mailing list for releases and other things would be nice. If no one else wants to set it up, I will. Any recommendations for places to do it? (FWIW, I dislike mailman)

**Comment by pydanny** [comment]
Created #367 and am now closing this issue.

**Comment by hackebrot** [comment]
Can you please enable the hook in the repo settings? @audreyr @pydanny :bow:
