### ISSUE TITLE
Exposing the configured context to the hooks.

### ISSUE THREAD

**Issue by gregmuellegger** [audreyr/cookiecutter#321]
I want to utilize my `pre_gen_project` hook to check whether the user-entered configuration is valid. For example if you have this `cookiecutter.json` file:
```json
{
    "repo_name": "whatever",
    "use_experimental_features": "yes",
    "year": 2014
}
```

Then I would like to validate that:

1. `"year"` is set to an integer.
2. `"use_experimental_features"` is either `"yes"` or `"no"`.

I think there is currently no way to achieve this. So what I propose is to
find a way to pass the configured context to the hooks. I can think of a few
methods:

1. Passing a JSON string via stdin
2. Passing a JSON string as argument to the script
3. Setting an environment variable (`$COOKIECUTTER_CONTEXT`) with the contents of the context (a JSON string)

I highly prefer the third method, since this would not break any existing scripts and can be easily retrieved by the hooks.

If the hook then finds an issue with the input, it would print an error message and exit with a status code to indicate cookiecutter that no further processing of the project shall be made.

I would like to implement this, but first wanted to check if you would be interested in a pull-request. Including tests and docs ofcourse ;)
What do you think of this feature? Is it worth including into cookiecutter?

**Comment by Osmose** [comment]
I think https://github.com/audreyr/cookiecutter/commit/d9b7079d0bd89d380e5569d655ebd2e94ffe784d solves the context injection part already, as the hooks are also rendered as templates prior to being run. Thus something like this might work:

```python
#!/usr/bin/env python
import json
import os
import sys


def main():
    if '{{ cookiecutter.use_experimental_features }}' in ('yes', 'no'):
        sys.stderr.write('`use_experimental_features` is not either `yes` or `no`. Aborting.')
        sys.exit(2)
    if not '{{ cookiecutter.year }}'.isdigit():
        sys.stderr.write('`year` is not set to a valid integer. Aborting.')
        sys.exit(2)


if __name__ == '__main__':
    main()
```

So maybe the real bug here is being able to abort generation from the pre_gen_project hook?

**Comment by hackebrot** [comment]
Please see #549 :bow:
