### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by steveoh** [audreyr/cookiecutter#354]
This [line](https://github.com/audreyr/cookiecutter/blob/8d3bc4a9df91fea68cb3d6e9d07672f25e7e8906/cookiecutter/compat.py#L64) fails on windows when a `cookiecutter.json` file has funny characters. Like [this one for example](https://github.com/ionelmc/cookiecutter-pylibrary-minimal/commit/b77a1d2cc2b8f2501a5538f2ba0ba475ef124249). After removing the funny characters the generator ran. Thoughts?

**Comment by michaeljoseph** [comment]
I think this should be a documentation fix for cookiecutter template authors: "Don't specify non-ASCII (?) characters in default values if you want your template to work on terminals with limited character support".
@pfmoore @steveoh @pydanny

**Comment by pfmoore** [comment]
@michaeljoseph Not really, a non-ASCII character in a default value is entirely legitimate. It's just that when displaying it in a prompt you need to take into account the fact that the terminal may not support displaying it correctly. Using a suitable error handling strategy ("backslashreplace" is probably the best, as it will display anything, and does so in a way familiar to most programmers) to ensure the default value can be printed is the correct answer.

**Comment by hackebrot** [comment]
Closing this as we use **click** for prompts now. The mentioned line does not exist anymore.

Please get back if you run into this problem again. :bow:
