### ISSUE TITLE
cookiecutter.json variables being presented as plain text in prompt

### ISSUE THREAD

**Issue by italomaia** [audreyr/cookiecutter#363]
Hello folks.

Following this: http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#basic-example-templates-in-context

I made this:
``` cookiecutter.json
{
    "author": "Your Name",
    "author_email": "{{ cookiecutter.author|lower|replace(' ', '.') }}@gmail.com"
}
```

While creating a new project, prompt gave me this:

author (default is "Your Name")? Italo Maia
author_email (default is "{{ cookiecutter.author|lower|replace(' ', '.') }}@gmail.com")?

Shouldn't the second line ask: "author_email (default is "italo.maia@gmail.com")?"

**Comment by michaeljoseph** [comment]
Hi @italomaia, unfortunately, that functionality is only in 0.9.0, which hasn't been released yet.

**Comment by pydanny** [comment]
I'm trying to get the 0.9.0 release out today. :construction_worker:

**Comment by pydanny** [comment]
0.9.0 is tentatively out on PyPI. I've tested the download and it works fine. If others could do the same that would be very handy.
