### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by daenney** [audreyr/cookiecutter#366]
We use cookiecutter at Spotify quite a bit but every now and then a new release breaks our templates and we need to update them. This is not a big deal and totally understandable pre 1.0.0 but we were wondering if anyone has given any thought to a versioning policy post 1.0.0?

This is just so we know what to expect and how close we should keep track of the releases of the project, set up some alerting around new releases and so on.

**Comment by michaeljoseph** [comment]
@daenney we do our best to [semantically version](https://github.com/audreyr/cookiecutter/blob/master/docs/core_committer_guide.rst#L123) and will continue to do so post 1.0.0.

Do you have any examples of breaking releases?
We should probably add some testing with actual template projects to our release checklist...

**Comment by pydanny** [comment]
I agree with @michaeljoseph, we do try to follow semantic versioning. In fact, as far as we know nothing about 0.9.0 should have broken anything with templates that worked under 0.8.0. If that is the case, if you can provide specifics then we can treat your problems as a bug report.

FWIW, the breaking change for 1.0.0 is the removal of support for Python 2.6.

**Comment by michaeljoseph** [comment]
@pydanny @daenney we've found a 0.9.0 regression: #368

**Comment by pydanny** [comment]
@daenney Is this the bug that is causing problems?

**Comment by daenney** [comment]
My apologies for not getting back to you earlier. That's exactly the issue we ran into yes.

**Comment by pydanny** [comment]
@daenney, @michaeljoseph Tomorrow morning before work I'll release 0.9.1 which will patch this issue.

**Comment by daenney** [comment]
@pydanny Awesome. Thank you!

**Comment by pydanny** [comment]
I moved up the schedule and just released on PyPI: https://pypi.python.org/pypi/cookiecutter/0.9.1

Please test manually! I need a confirmation it's all good before I announce it publicly.

**Comment by daenney** [comment]
Works just fine now!

**Comment by pydanny** [comment]
Happy we could help you. All the credit for this one goes to @jacebrowning.
