### ISSUE TITLE
Documentation for more advanced templating behavior

### ISSUE THREAD

**Issue by ftobia** [audreyr/cookiecutter#373]
On a whim I tried out a template like the following, to see if it would work (in its own file):

    {% cookiecutter.switch %}
    foo
    {% else %}
    bar
    {% endif %}

This works the way I would expect. I think that conditional output is awesome and powerful, likewise looping constructs. I didn't see it documented (though I could be mistaken).

Is this an "official" feature you'd like to see documented and perhaps tutorial-ized?

**Comment by pydanny** [comment]
Yes, we would like to have this documented! A tutorial would be great too!

FWIW, you can even include conditionals in file and directory names! The downside is that conditionals in file and directory names don't yet work on Windows. So if you mention this, please include a warning about using this trick on Windows.

**Comment by ftobia** [comment]
Awesome, thanks. I will try to get to this over the coming weeks.

**Comment by hackebrot** [comment]
Cookiecutter uses [jinja2](http://jinja.pocoo.org/docs/dev/), so anything that works for the given jinja2 version, is also available for cookiecutter templates.

Feel free to submit a PR to add a new tutorial to the [section in the docs](http://cookiecutter.readthedocs.org/en/latest/tutorials.html#create-your-very-own-cookiecutter).

Thanks :bow:
