### ISSUE TITLE
Improve the local machine virtualenv test story

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#377]
If you are manually testing instead of using `tox`, to determine the test requirements is too challenging. While we should be testing in `tox`, this is a barrier to easily working on Windows.

Proposals:
- Document the test requirements
- Provide a `test_requirements.txt` file.

**Comment by ionelmc** [comment]
Did I misunderstand or you really stated that tox is a barrier on Windows?!

**Comment by pydanny** [comment]
@ionelmc Somewhere along the way I thought that tox was not windows friendly. A documentation check against tox informed me that I was wrong.
