### ISSUE TITLE
Ability to loop through cookiecutter variables

### ISSUE THREAD

**Issue by wldcordeiro** [audreyr/cookiecutter#383]
In a cookiecutter.json, is it possible to have a structure like this or similar.
```
{
  "range": "3",
  {% for i in cookiecutter.range %}
    "var_name": "var_value",
  {% endfor %}
}
```

For my particular example I'm interested in piping the values over into ansible playbooks that then create databases for development environments. I'm just curious if the recent additions of Jinja power to the cookiecutter.json allow this kind of functionality.

**Comment by michaeljoseph** [comment]
@wldcordeiro we currently only support rendering key values as Jinja templates: https://github.com/audreyr/cookiecutter/pull/291.

**Comment by wldcordeiro** [comment]
@michaeljoseph I saw that this was closed but is there any plan to add this?
