### ISSUE TITLE
.cookiecutterrc and cookiecutters_dir not working as I expected

### ISSUE THREAD

**Issue by apapanico** [audreyr/cookiecutter#385]
Hi,
Here's the setup:
+ I have a ~/.cookiecutterrc as talked about here: http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html
+ I also have a cookiecutters_dir at ~/.cookiecutters/ with the subdirectory cookiecutter-pypackage/.

When I try to run "cookiecutter cookiecutter-pypackage/" in ~/Projects/, I get the following error

    Traceback (most recent call last):
      File "/opt/anaconda/bin/cookiecutter", line 9, in <module>
        load_entry_point('cookiecutter==0.9.0', 'console_scripts', 'cookiecutter')()
      File "/opt/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 590, in main
        rv = self.invoke(ctx)
      File "/opt/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/opt/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/Users/alexp/Projects/cookiecutter/cookiecutter/cli.py", line 70, in main
        cookiecutter(template, checkout, no_input)
      File "/Users/alexp/Projects/cookiecutter/cookiecutter/main.py", line 95, in cookiecutter
        extra_context=extra_context,
      File "/Users/alexp/Projects/cookiecutter/cookiecutter/generate.py", line 43, in generate_context
        file_handle = open(context_file)
    IOError: [Errno 2] No such file or directory: u'cookiecutter-pypackage/cookiecutter.json'

This error shows up if I either do pip install or with the git repo locally.  Naturally, it makes a bit of sense.  There is no directory ~/Projects/cookiecutter-pypackage/.  

However, and perhaps I'm making a poor assumption about usage, it seems to me if I clone or otherwise create a cookiecutter and it's sitting in cookiecutters_dir, it'd be nice to just refer to it as I did above.  For my usage, if I create a cookiecutter, I don't particularly want it sitting around a Projects directory, especially if I have multiple project directories for personal and organizational purposes.

In order to do this, I added three lines to main.py in my fork (see below) and it seems to work.  I did it as an `elif` to try to preserve the possibility of a lack of a cookiecutters_dir.  I have not written a test for this and admittedly I don't really know how.  I will likely just use my fork with this modificationgoing forward but I wanted to let the developer crew know about this.  

Cheers.

    # cookiecutter.main
    ...
    # TODO: find a better way to tell if it's a repo URL
    if 'git@' in template or 'https://' in template:
        repo_dir = clone(
            repo_url=template,
            checkout=checkout,
            clone_to_dir=config_dict['cookiecutters_dir'],
            no_input=no_input
        )
    #### Added these three lines
    elif 'cookiecutters_dir' in config_dict:
        cookiecutters_dir = os.path.expanduser(config_dict['cookiecutters_dir'])
        repo_dir = os.path.join(cookiecutters_dir,template)
    else:
        # If it's a local repo, no need to clone or copy to your
        # cookiecutters_dir
        repo_dir = template

**Comment by michaeljoseph** [comment]
Hi @apapanico, thanks for reporting this issue.
I think we can definitely improve the user experience here.

We do check if there is an existing checkout inside the call to [`clone`](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/vcs.py#L104-L105), but we only support deleting and re-cloning out the repo.

I think we should be detecting existing templates (for both repo URL and repo name variants) and then presenting a choice to either:
- delete and re-clone the repo
- pull the repo
- use the existing checkout

Thoughts?

**Comment by apapanico** [comment]
Interesting.  I guess I was more thinking of having a cookiecutter that wasn't a repo somewhere so I could just build one for my needs, stash it in ~/.cookiecutters and call it by name.

And in line with how the repos are stored in ~/.cookiecutters, after you get a cutter from a repo on github you could just call it again by name.

**Comment by Kreger51** [comment]
As a recent user of cookiecutter, I agree with the suggested change. I too, thought that one could stash templates in ``~/.cookiecutters`` and then call them by name, without specifying the directory.

**Comment by sundeer** [comment]
Just ran into this myself and left me scratching my head a bit.

**Comment by michaeljoseph** [comment]
Re-visiting this one, and my current plan is:

- [ ] Gracefully handle the case where the code assumes we're referencing a local filesystem repo, but it doesn't exist (#652)
- [ ] After trying repository URLs and local repos, check if we have a match for an existing directory in `~/.cookiecutters` and use that
- [ ] When we're trying to clone a remote repo to `~/.cookiecutters`, but there's already something there, allow users to use the existing repo directory if the decide not to delete and re-clone.

**Comment by brianrusso** [comment]
This happened to me on a brand-new cookiecutter install.

E.g.

```
brian@maunaloa:[~]$ rm -rf ~/.cookiecutters/
brian@maunaloa:[~]$ cookiecutter  gh:jackstouffer/flask-foundation
Cloning into 'flask-foundation'...
remote: Counting objects: 566, done.
remote: Total 566 (delta 0), reused 0 (delta 0), pack-reused 566
Receiving objects: 100% (566/566), 1.40 MiB | 1.87 MiB/s, done.
Resolving deltas: 100% (231/231), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/cli.py", line 106, in main
    config_file=user_config
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/main.py", line 130, in cookiecutter
    extra_context=extra_context,
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/generate.py", line 92, in generate_context
    with open(context_file) as file_handle:
IOError: [Errno 2] No such file or directory: u'/home/brian/.cookiecutters/flask-foundation/cookiecutter.json'
brian@maunaloa:[~]$ cookiecutter --version
Cookiecutter 1.4.0 from /usr/local/lib/python2.7/dist-packages (Python 2.7)


```
