### ISSUE TITLE
Strange idea of what now is

### ISSUE THREAD

**Issue by mark0978** [audreyr/cookiecutter#386]
For some reason cookiecutter thinks it is still January 13th even though it is Feb 6th
Got this will creating a django project from a slightly modified cookiecutter-django repo
```
version (default is "0.1.0")? 
now (default is "2015/01/13")? 
year (default is "2015")? 
$ cookiecutter --version
Cookiecutter 0.9.1 from /usr/local/lib/python2.7/dist-packages (Python 2.7)
$ date
Fri Feb  6 10:03:16 CST 2015
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

```

**Comment by pydanny** [comment]
Very weird. Cookiecutter knows nothing about dates. Can you link to the repo in question? Otherwise there is nothing that can be done.

**Comment by mark0978** [comment]
Found the issue in your repo

https://github.com/pydanny/cookiecutter-django/blob/master/cookiecutter.json

has **now** in the cookiecutter.json

**Comment by hackebrot** [comment]
This looks like a feature for the template itself to me. The following may be a starting point:
https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#example-injecting-a-timestamp

**Comment by hackebrot** [comment]
FYI #154 #155 :point_left:

**Comment by michaeljoseph** [comment]
@mark0978 Closing this because [pydanny/cookiecutter-django](https://github.com/pydanny/cookiecutter-django/blob/master/cookiecutter.json#L10) has an outdated date, not cookiecutter.
