### ISSUE TITLE
Support cloning with specific branches

### ISSUE THREAD

**Issue by ionelmc** [audreyr/cookiecutter#397]
Eg: `cookiecutter gh:user/repo@develop`

**Comment by jhermann** [comment]
Should be handled by the v1.0 "--checkout" option. So this can be closed‽

**Comment by ionelmc** [comment]
The `@soemthing` still looks nicer imo.

**Comment by hackebrot** [comment]
I'd rather not change the behavior that @jhermann mentioned.

Think we are fine with it for now unless you do have strong arguments against it. In which case I will be happy to re-open this issue, @ionelmc. :bow:

**Comment by ionelmc** [comment]
@hackebrot the sole reason was that pip does this, eg: https://pip.pypa.io/en/stable/reference/pip_install/#git

But yeah, now that `--checkout` is released, it's prolly just overcomplication.

**Comment by hackebrot** [comment]
I think so, yeah. Thank you @ionelmc for the explanation though.
