### ISSUE TITLE
Pending pytest PRs

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#399]
Hey there,

I don't mean to cause hysteria as I completely understand that you all have plenty of things to do apart from Cookiecutter!

Most of my PRs that impact the test suite are still pending. By now I am a bit worried that it's gradually getting harder to merge them. I noticed that there is at least one PR which causes a confict with the current master :worried:

I think that these changes greatly improve our test suite, so I kindly want to ask you if there is anything that I can do to aid you in this matter. I'll be happy to help!!! :blush:

https://github.com/audreyr/cookiecutter/pulls/hackebrot

:bell: @audreyr @pydanny @pfmoore @michaeljoseph

**Comment by pydanny** [comment]
@hackebrot Thanks for responding to my request to point me back on track. I'm trying to work out a plan so I can get back to reviewing pull requests again on a daily basis. I'll start going through PRs right now.

**Comment by hackebrot** [comment]
Cool! :heart_eyes: Ping me if you need any help!

**Comment by michaeljoseph** [comment]
@hackebrot Just 2 PR left needing rebase...

**Comment by pydanny** [comment]
All done
