### ISSUE TITLE
AppVeyor failing on master

### ISSUE THREAD

**Issue by msabramo** [audreyr/cookiecutter#401]
I just submitted a PR (#400) and it's flagged as failing tests because it failed tests on AppVeyor but that seems to also be an issue on `master`.

So we should probably fix that issue or if it's non-trivial, maybe at least disable AppVeyor for pull requests?

**Comment by pydanny** [comment]
The fix is probably trivial, but requires Windows expertise I can't use without a local Windows box. Unfortunately, I won't be able to access that until Monday.

In the meantime, we'll just continue to let things fail rather than hide the issue.

**Comment by msabramo** [comment]
This issue was fixed by https://github.com/audreyr/cookiecutter/pull/403
