### ISSUE TITLE
DistributionNotFound error when running tox

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#404]
Hi,

@pydanny discovered that the test suite is broken at the moment. The according tests are coincidentally skipped on Travis. :cry:

Running `py.test` itself doesn't show any errors at all. However `tox -e py27` does:
```python
...
tests/test_more_cookiecutters.py:67: AssertionError
...
pkg_resources.DistributionNotFound: click<4.0
```

`git bisect` reports that the suite broke back when we switched to `click` in 9317f39.

Apparently setting up a fresh virtualenv did the trick for me:
```
  py27: commands succeeded
ERROR:   py33: InterpreterNotFound: python3.3
  py34: commands succeeded
  pypy: commands succeeded
  flake8: commands succeeded
```
Can you confirm this?

**Comment by pydanny** [comment]
Everything looks okay to me. Should we leave this open or close it?

**Comment by hackebrot** [comment]
I'd say we close this at this point.  :relaxed: 

In case someone experiences this problem we know where to look first.
