### ISSUE TITLE
Enable codecov.io pull request comment and build status

### ISSUE THREAD

**Issue by michaeljoseph** [audreyr/cookiecutter#416]
@audreyr, only you have the power to click these buttons.
https://codecov.io/github/audreyr/cookiecutter

**Comment by michaeljoseph** [comment]
![screen shot 2015-03-15 at 18 46 47](https://cloud.githubusercontent.com/assets/169933/6656946/731d3752-cb43-11e4-9952-a1dde6a9f763.png)

**Comment by ionelmc** [comment]
@michaeljoseph How is codecov.io better than coveralls?

**Comment by pydanny** [comment]
@ionelmc - coveralls changed the percentages every time, including when the only changes were documentation based.

**Comment by luzfcb** [comment]
@pydanny another service to perform tests. 
"Landscape.io is a code quality inspector for Python codebases. It inspects your code to find errors, possible problems, security issues."

see some examples of reports:
https://landscape.io/github/luzfcb/django-crispy-forms/6
https://landscape.io/github/luzfcb/django-crispy-forms/6/messages
https://landscape.io/github/luzfcb/django-crispy-forms/6/modules

I liked the inline comments explaining the problem:

https://landscape.io/github/luzfcb/django-crispy-forms/6/modules/crispy_forms/layout.py#L346

finally, there is almost no problems with cookiecutter:
https://landscape.io/github/luzfcb/cookiecutter/1/modules

**Comment by audreyr** [comment]
I flipped all the switches for Pull Request Comment. If it's too much commenting, let me know what to change.
![screen shot 2015-03-31 at 8 26 04 pm](https://cloud.githubusercontent.com/assets/74739/6934106/3cbca816-d7e4-11e4-8e20-0f3cd9b68ac3.png)

I also flipped the switch for Github Build Status and set it to 95%. Let me know if that's too high/low.
![screen shot 2015-03-31 at 8 29 27 pm](https://cloud.githubusercontent.com/assets/74739/6934125/ada51ac2-d7e4-11e4-8f19-afc325854006.png)

If I need to change anything else, you can reopen this. (Sorry about missing this earlier! If I'm a blocker for anything similar in the future, don't hesitate to ping me off-Github or ask @pydanny to bother me.)

@luzfcb, thanks for the Landscape.io info! I just imported audreyr/cookiecutter into it now. It's thinking...

**Comment by hackebrot** [comment]
I'm afraid it still not working for PRs, please see #447 

:bell: @audreyr @michaeljoseph
