### ISSUE TITLE
Docs on the routine for accepting template PRs

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#421]
Hey there,

I couldn't find any explanations on how to validate that a template is working fine. From what I remember Audrey always checks that it is working fine for all platforms?! :sweat_smile:

http://cookiecutter.readthedocs.org/en/latest/core_committer_guide.html#core-committer-guide

I'll be happy to write a brief guide on how to do it, if you provide me with the necessary information.

:bell: @audreyr @pydanny @pfmoore @michaeljoseph

**Comment by pydanny** [comment]
The means by which we accept template PRs:

1. Run the template to generate the project.
2. Attempt to start/use the rendered project.
3. Merge the template in.
4. Update the history file (adding a template doesn't give you authors credit).
