### ISSUE TITLE
Hooks are written using 'ascii' encoding after expansion

### ISSUE THREAD

**Issue by jhermann** [audreyr/cookiecutter#427]
`tempfile.NamedTemporaryFile()` takes an encooding parameter in Py3, but not so in Py2. If a hook file contains non-ascii chars, writing the tmpfile fails.

Fixing this likely involves a "compat" extension that adds the encoding paramter to a wrapper class on Py2, and then uses that in "write".

**Comment by hackebrot** [comment]
https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/hooks.py#L97 :white_check_mark:
