### ISSUE TITLE
Suggestions for standardized names for cookiecutter templates

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#430]
@michaeljoseph has brought this up before. We've seen people call Cookiecutter templates a lot of things:
- `cookiecutters` - A personal favorite, as it means you would say, 'Cookiecutter cookiecutters'. 
- `templates`
- `molds`
- `moulds` -  Cookiecutter was named after the American concept of cookies, but mould is the British spelling of `mold`. 

I want to put this up for a vote, and will be putting up a form in a day or so. Nominate your own in the comments, if it sounds good we'll add it to the vote!

**Comment by jhermann** [comment]
Another rather technical term is “archetypes” (e.g. used by Maven) – unfortunately with no relation to cookies whatsoever. :smiley_cat:

**Comment by vaab** [comment]
Let's keep it simple: I would go for ``templates``... Why exactly do you want a special name ? Templating is done by a awful lot of tools in every language, I'm pretty happy they didn't try to invent a new word that is far from being clear for people outside the project.

**Comment by hackebrot** [comment]
``cookiecutters`` :+1:

**Comment by khorn** [comment]
I'm :-1: on `templates`, because (to me at least) a template already has a meaning in the context of Jinja2.  That is, a template is a file containing Jinja2 instructions.

What we're talking about here is a group of those, so I think it should be named differently.

**Comment by michaeljoseph** [comment]
`cookiecutters` :+1:

**Comment by sveetch** [comment]
`cookiecutters` :+1: because like it was said before, template allready have a strong meaning in web projects

**Comment by jcdyer** [comment]
flavors

**Comment by DeveloperMal** [comment]
:+1: for cookiecutters. I think just using the word cookies doesn't fit the context of what the application does.

**Comment by hackebrot** [comment]
Cookiecutters 👈
