### ISSUE TITLE
Pending template PRs

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#435]
There are a bunch of PRs that add a **cookiecutter** to the readme.
#423 #422 #374 #350 #307 #283 #278 #143 #131

Some of them cause merge conflicts or require additional work, others should be just fine.

I think we should try to address them asap and close the ones that are obsolete.

I decided to create this issue as I cannot add labels :blush: 
https://github.com/audreyr/cookiecutter/labels/template

What's your opinion on this matter?

**Comment by pydanny** [comment]
Should we review these or pull requests that add technical features?

**Comment by hackebrot** [comment]
I feel that we should try to ship http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render soon. :smiley: 

Hence I'd rather have a few more templates in the release instead of additional features. Do you know of any critical issues that need to be tackled asap?

**Comment by hackebrot** [comment]
I was thinking about merging all of the template contributions in myself. What's your opinion on this matter? @audreyr @pydanny @pfmoore @michaeljoseph

**Comment by hackebrot** [comment]
:bell:

**Comment by audreyr** [comment]
Go for it. I like to actually check the template to see if and how it works before merging, but it's not necessary.

**Comment by michaeljoseph** [comment]
These are all closed now.

**Comment by hackebrot** [comment]
@michaeljoseph 👍
