### ISSUE TITLE
Compatibility with Python 2.7.9

### ISSUE THREAD

**Issue by pbazard** [audreyr/cookiecutter#436]
I had no issue with cookiecutter prior to python 2.7.9. Now when I run cookiecutter I get a `ImportError: No module named mock` due to (I guess) this variable `OLD_PY2 = sys.version_info[:2] < (2, 7)` in compat.py. I just forked it and changed to `<=` and it works fine but I do not know if it was intended.

**Comment by hackebrot** [comment]
Hi @pbazard 

are you using the PyPI package or the development version? As you mentioned that it was working for your fork I assume you did use the development setup beforehand. Did you try it with a fresh ``virtualenv``?

Could you please also provide us with a traceback of the ``ImportError``?

Cheers :bow:
Raphael

**Comment by pbazard** [comment]
Hi Raphael

I just followed DG procedure [here](https://github.com/pydanny/cookiecutter-django) with a new and empty `virtualenv`. That's what I used to do when I was in Python 2.7.6.
Now, with Python 2.7.9 I had this error:

    Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/2.7/bin/cookiecutter", line 7, in <module>
    from cookiecutter.cli import main
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-  packages/cookiecutter/__init__.py", line 10, in <module>
    from .compat import OLD_PY2
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-   packages/cookiecutter/compat.py", line 30, in <module>
    from mock import patch
    ImportError: No module named mock.

I just "patched" this file and add `<=` in order to get True for `OLD_PY2`.

**Comment by hackebrot** [comment]
Hmm that's odd. :no_mouth: 

I just tried it with a fresh **virtualenv** and **Python 2.7.9** and it was working just fine. It successfully created a project from [cookiecutter-django](https://github.com/pydanny/cookiecutter-django).

Looking into the code from the [latest release](https://github.com/audreyr/cookiecutter/releases/tag/1.0.0) I found the following occurrences of ``OLD_PY2``:

```bash
$ grep -Hwn OLD_PY2 $(find cookiecutter -name '*.py')
cookiecutter/compat.py:5:OLD_PY2 = sys.version_info[:2] < (2, 7)
cookiecutter/__init__.py:10:from .compat import OLD_PY2
cookiecutter/__init__.py:14:if OLD_PY2:
```
Your changes should in fact result in a ``DeprecationWarning``, please see https://github.com/audreyr/cookiecutter/blob/1.0.0/cookiecutter/__init__.py#L14

Running ``pip install cookiecutter`` automatically installs **mock** for **Python 2**, please see https://github.com/audreyr/cookiecutter/blob/master/setup.py#L39

Are you sure that you are running **cookiecutter (1.0.0)**?

Not really sure how to help in this matter :worried: 

cc @audreyr @pydanny

**Comment by hackebrot** [comment]
Closing this for now. Please let me know in case this is still an issue.
