### ISSUE TITLE
Run cookiecutter over an existing project

### ISSUE THREAD

**Issue by driesdesmet** [audreyr/cookiecutter#458]
Sometimes, I want to overwrite what's already in a project structure with what is in my cookiecutter template. This is not allowed now. I think it would be a good idea to issue a warning but allow it, like yeoman does it. Most of the time (like always) my code is under version control, so if it wasn't intended, I could always roll back.

**Comment by hackebrot** [comment]
Hi @driesdesmet! :wave: 

We merged #493. Please let us know in case it's not working for you! :bow:
