### ISSUE TITLE
Dict values in extra_context are converted to strings.

### ISSUE THREAD

**Issue by viswanathct** [audreyr/cookiecutter#461]
The following code isn't working as expected:

```Python
extra_context = {
	
	'template': {'name': 'package a'}
}

cookiecutter('template_dir', extra_context=extra_context)
```

When rendering **{{  cookiecutter.template.name }}**, an empty string is rendered.

The problem lies in **prompt.prompt_for_config**.

The statement
```Python
raw = raw if is_string(raw) else str(raw)
```
converts any **dict** into **str**.

And the following chage fixes the issue
```Python
if isinstance(raw, dict):
            cookiecutter_dict[key] = raw
            continue
			
        raw = raw if is_string(raw) else str(raw)
```

**Comment by hackebrot** [comment]
#815 changed the way dictionaries are handled. Can you please give it a try?

**Comment by viswanathct** [comment]
Sadly, I've lost touch with it.

**Comment by hackebrot** [comment]
Okay, that's fair enough. I'm closing this for now.

Please get in touch if you see any problems around this in the future. Thanks 🙇
