### ISSUE TITLE
Stop build if pre hook fails

### ISSUE THREAD

**Issue by thoppe** [audreyr/cookiecutter#464]
There may be a way to do this already, but the documentation for hooks isn't complete. If we have a pre-hook file that is simply

    raise SyntaxError

it would be nice to halt the cookiecutter process here. What I envision is a pre-hook file that checks for certain external dependencies before continuing. It would be to fail out here before the template is pulled and rendered.

**Comment by thoppe** [comment]
I've asked the question on SO here and I'll post any response I get:

http://stackoverflow.com/q/31128808/249341

**Comment by pydanny** [comment]
I don't believe raising an exception will stop a `pre-hook` right now, as those are run as subprocesses (https://github.com/audreyr/cookiecutter/blob/256cd6f4b3ebd684887406713fb966d829f8d7d1/cookiecutter/hooks.py#L65-L69). Of course, I could be wrong -- I'm just not in a place where I can test this issue right now.

However, if this doesn't exist now, we can add that functionality in a future release.

**Comment by thoppe** [comment]
I found that code block as well. Couldn't we try to catch any errors on the subprocess call and raise an exception right there? It seems like it shouldn't be hard (famous last words). I can try a hack at it if you like, though I've never done any testing suites so I would need help putting a unit test in.

**Comment by hackebrot** [comment]
Hi @thoppe, we merged #549 by @eliasdorneles.

Closing this for now. Please let us know if it helps! Thanks :bow:

**Comment by thoppe** [comment]
Thanks @eliasdorneles!
