### ISSUE TITLE
Instructions for local development are incomplete.

### ISSUE THREAD

**Issue by spookylukey** [audreyr/cookiecutter#466]
When executing the line:

    python setup.py test

as directed, I get the following error:

    running test
    Traceback (most recent call last):
      File "setup.py", line 111, in <module>
        tests_require=test_requirements
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setup.py", line 60, in run
        import pytest
    ImportError: No module named pytest

I'm not sure what you are supposed to do to install the 'tests_require' dependencies.

**Comment by pydanny** [comment]
That's supposed to happen automatically when running `python setup.py test`. I look into it over the holiday weekend.

**Comment by hackebrot** [comment]
I can confirm this issue. :worried: 

It seems to be a problem with our `PyTest` Command. Setuptools comes with a TestCommand that does consider `tests_require` whereas Distutils doesn't.

**Comment by pydanny** [comment]
@hackebrot Didn't you suggest we get off of `Setuptools` or `Distutils`?

**Comment by hackebrot** [comment]
Well, from what I know `setuptools` is a standard pretty much. If we all agree on dropping `distutils`, I will happily integrate `tox` and solve this very issue.

cc @audreyr @pydanny @michaeljoseph
