### ISSUE TITLE
Ask before writing into an existing project directory

### ISSUE THREAD

**Issue by lgp171188** [audreyr/cookiecutter#470]
I have an existing Django project that does not use the cookiecutter-django template. When running ``cookiecutter https://github.com/pydanny/cookiecutter-django``, it writes into the project directory even if it already exists without warning the user about it.

The correct behaviour would be to abort if the project directory already exists or at least warn the user and ask for confirmation before writing into the existing directory.

I have raised an issue in the cookiecutter-django project for this - https://github.com/pydanny/cookiecutter-django/issues/265

After having a quick look at the source for cookiecutter-django, it looks like this could be an issue with cookiecutter.

**Comment by pydanny** [comment]
:+1: to a patch.

**Comment by hackebrot** [comment]
Resolved and merged! :ok_hand:
