### ISSUE TITLE
Why does cookiecutter depend on click<4.0?

### ISSUE THREAD

**Issue by SpotlightKid** [audreyr/cookiecutter#472]
When I change the requirements in `setup.py` to just require 'click' without a version spec, and use cookiecutter with click 4.0, it seems to work without problems.

Depending on an old version of click causes problems with distribution packaging, e.g. here:

https://aur4.archlinux.org/packages/python-cookiecutter/

**Comment by SpotlightKid** [comment]
All tests pass with click==4.0 and Python 3.4 and 2.7

**Comment by pydanny** [comment]
Cookiecutter specifies `click<4` because we didn't know before click 4.0 came out if the click API would change or not. If the API did change and crashed Cookiecutter universally that would have been a problem. 

We'll try and get a new release out in the next few days with updated requirements.

**Comment by SpotlightKid** [comment]
Fair enough.

**Comment by pydanny** [comment]
Fixed, will be addressed in the forthcoming 1.1.0 release.

**Comment by vincentbernat** [comment]
Just for info, in Debian, I'll remove the version constraint. Otherwise, cookiecutter just breaks each time a new version of click is available. Doesn't click's author commit to some kind of backward compatible API that would not break suddenly?

**Comment by pydanny** [comment]
We'll try to get out a new version shortly. Cookiecutter is ready, it's just a matter of the time involved.
