### ISSUE TITLE
extra_context via the command line?

### ISSUE THREAD

**Issue by thomaslee** [audreyr/cookiecutter#477]
@michaeljoseph's work on #260 & #274 introduced the `extra_context` parameter and at one point an `--override` option to set extra_context vars via the command line, it was suggested that perhaps `--parameter` would be better, but ultimately @audreyr decided against including either at the time (per https://github.com/audreyr/cookiecutter/pull/260#issuecomment-54107644 )

Any new thinking on this? I personally find it a bit jarring to be prompted for every single template var when I only really care about the repo/project name (for example). `--no-input` is part of the solution, but the other part is being able to set template vars from the command line.

For now I'll likely hook up a small wrapper script to call out to the cookiecutter module, so no huge deal -- mostly just trying to keep the conversation open.

**Comment by grahamlyons** [comment]
I'd really like this - I have exactly the same use case: I just want to take a project name and then generate the class name, repo name etc. from that using the default behaviour.

**Comment by grahamlyons** [comment]
The work is there in #400.

**Comment by pydanny** [comment]
Closing this as resolved.
