### ISSUE TITLE
Allow for partial template application

### ISSUE THREAD

**Issue by babilen** [audreyr/cookiecutter#486]
One drawback of cookiecutter is that more complex templates have to be instantiated in toto. While this might be appropriate in some cases, it overwhelms new users and developers of new projects alike and also causes the proliferation of `foo-minimal` templates that simply differ from the non-minimal one in that they exclude certain, unnecessary, parts of the template.

Say you want to develop a new Python application and start your projects by running `cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git`. This causes quite a mental overload in that users have to pay attention to various aspects of Python development, packaging, testing and licensing at once, simply due to the fact that files corresponding to these appeared in your project and *demand* attention.

I would propose to define and implement a way in which parts of the template can be defined as 'default' and other parts can be named, but wouldn't normally be generated. The general idea is a workflow such as:

```
new-project $ cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git
→ cookiecutter asks questions and instantiates a minimal template that follows
  pypa's recommendations

new-project $ cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git license
→ cookiecutter asks questions and instantiates templates pertaining to the licensing 
  of the project, such as LICENSE

new-project $ cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git docs
→ user wants to start working on documentation so the sphinx bit is being 
  instantiated
...
```
A workflow such as this would allow users to focus on specific aspects of their project at a time and also makes templates much more powerful. It would, however, require changes to the configuration of templates in that one has to be able to group questions and templates under a specific name.

This issue is probably related to #126 and #467, but takes a slightly different approach in that different "areas" of a template have to be made explicit.

**Comment by audreyr** [comment]
Interesting idea. I think such a feature would add more complexity to Cookiecutter than I'd like, but if anyone has further ideas about this, please comment here.

**Comment by babilen** [comment]
Well,  few people will comment on this as it has been closed.

**Comment by storax** [comment]
I had the same idea for this feature with the approach mentioned in #467 (don't process files if name evaluates to an empty string).
Right now, all files are rendered and one can delete files via hooks (like in [Audreyr Cookiecutter-Pypackage](https://github.com/audreyr/cookiecutter-pypackage)). In my opinion the proposed approach is much more straight forward. It is more explicit because one can see that a file is optional without looking at the hooks. When writing hooks, the user has to handle all the exception handling himself.

I would really like to implement this and add a PR if this feature gets accepted.
