### ISSUE TITLE
Noob tries to create it's own modipy extension

### ISSUE THREAD

**Issue by chasylexus** [audreyr/cookiecutter#488]
Hi everyone!
I am total noob in coding but I have good education in physics and mathematics and I want to try to create Deezer extension for mopidy.
So I've decided to use this instruments for extension creating.
I use guidelines for contributing and I have an issue with virtualenvwrapper.
Unfortunately, when I try to 'mkvirtualenv cookiecutter' I get this:
'-bash: mkvirtualenv: command not found'.
I've installed virtualenvwrapper. But I don't sure I've make it right.
My OS is OS X Yosemite.
How to install virtualenvwrapper properly?
Thank you very much!

**Comment by luzfcb** [comment]
This is not a problem of Cookiecutter.
The most probable is that you forgot to put `source /usr/local/bin/virtualenvwrapper.sh` to your shell startup file (on OS X, you can put this at the end of `~/.bash_profile` ).
Do not forget to close and open the terminal after performing this configuration.

Having said that, Google is your friend, results of search ["virtualenvwrapper mac os x"](https://www.google.com/webhp?q=virtualenvwrapper+mac+os+x&tbs=qdr:y) :

http://blog.manbolo.com/2014/09/27/use-python-effectively-on-os-x

https://jamie.curle.io/posts/installing-pip-virtualenv-and-virtualenvwrapper-on-os-x/
http://exponential.io/blog/2015/02/10/install-virtualenv-and-virtualenvwrapper-on-mac-os-x/
