### ISSUE TITLE
PyPI Crate.io badge problems in readme

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#491]
For some reason the badge is not displayed properly (Tested on Mac OS X - Firefox, Safarai and Win 7 - Chrome, Firefox) :worried: 

<img width="808" alt="cookiecutter_readme_badge" src="https://cloud.githubusercontent.com/assets/6024445/9135619/bb8ff806-3d0f-11e5-8af4-87ab49e8fc12.png">

**Comment by pydanny** [comment]
Switching shields.io for now as of 8c2974d70c7cf5cb78231cf6000a117f80f9259d, but that's likely a temporary solution.

**Comment by michaeljoseph** [comment]
https://github.com/badges/pypipins/issues/39

**Comment by michaeljoseph** [comment]
https://github.com/badges/pypipins/issues/37

**Comment by pydanny** [comment]
I feel sorry for @kura, hopefully he'll find some stability. In the meantime, sheilds.io.
