### ISSUE TITLE
Improve help access and prompts from the CLI

### ISSUE THREAD

**Issue by willingc** [audreyr/cookiecutter#492]
A new user might enter any of the following and expect to be guided to the Help information about using the CLI:
- `cookiecutter`
- `cookiecutter -h`
- `cookiecutter --h`
- `cookiecutter help`

It would be helpful to improve the CLI messages or handle some of the additional cases for a new user.

@audreyr Thanks for the handy tool :bouquet: 

<img width="773" alt="screen shot 2015-08-07 at 7 54 57 am" src="https://cloud.githubusercontent.com/assets/2680980/9138629/e64cb42a-3cd9-11e5-8c9c-cb9d726bd1eb.png">

**Comment by hackebrot** [comment]
Thank you @willingc for submitting an issue on this topic! :bow:

I agree that it would be very helpful to extend the help messages displayed to the user. As I was going over the CLI implementation just yesterday (#489) and noticed that the **click** does not support ``-h`` as a help option as it is not common in posix.

However I feel we should add ``cookiecutter`` and ``cookiecutter help``. :smile:

**Comment by audreyr** [comment]
Sure, we can start with `cookiecutter` and `cookiecutter help`. 

This would be a particularly good feature to have sooner than later, so I added please-help and high-priority tags.

**Comment by willingc** [comment]
@michaeljoseph Thanks for adding the help features :sunflower:

**Comment by hackebrot** [comment]
@michaeljoseph :+1:

**Comment by michaeljoseph** [comment]
Thanks guys, trying to ease back into things- I am a people pleaser at :heart: 
:heart_eyes: @willingc @audreyr @hackebrot
