### ISSUE TITLE
Allow overriding existing files

### ISSUE THREAD

**Issue by ionelmc** [audreyr/cookiecutter#493]
I've tried to use the cookiecutter from 75590ed66ca7ad14df62c4c43f53dd35253f606c but it give me an `Error: "python-nameless" directory already exists` if I try to regenerate a project.

Can this new behavior be reverted? What's the reason for disallowing updates?

**Comment by ionelmc** [comment]
Seems it was introduced in https://github.com/audreyr/cookiecutter/commit/5c22467db2ecb8d7fa36a16f8a0162be4fb3207e 

But there should be a way to switch this off. The original issue (#470) was about a prompt :-)

**Comment by hackebrot** [comment]
Please have a look at #475. Not too sure how to proceed on this.

Do you think overwriting an existing directory is the better option?

**Comment by ionelmc** [comment]
Override projects all the time. It works quite well as all my projects are under version control - so I can just revert if some file need not be changed.

**Comment by hackebrot** [comment]
Wouldn't it also remove your ``.git`` folder? :no_mouth:

**Comment by ionelmc** [comment]
Cookiecutter doesn't copy `.git` over. Not sure what's the reason.

**Comment by ionelmc** [comment]
This is the reason :) https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/find.py#L30

That directory will not have any `.git` in it. Template authors don't store a second `.git` dir in their templates AFAIK
