### ISSUE TITLE
Discovering all fieldnames of template

### ISSUE THREAD

**Issue by magonser** [audreyr/cookiecutter#504]
Hi together,

I have been using cookie cutter on few projects already and made my own template. I have read through the docu, but unfortunately not have found the following:

how can I discover, which filenames are present in a given template without looking into the respective .json file. The reason I ask this, is because I found it a bit cumbersome to build a template and keep manually track on which fieldnames I have put all over the template. Please forgive me, if I missed out on something. I would appreciate a pointer in t he right direction. 

Thanks, M.

**Comment by pydanny** [comment]
Hi @magonser, Cookiecutter itself doesn't provide this capability. However, it shouldn't be hard to write a Python script that walks through your templates directory structure and look for anything that begins with `{{ cookiecutter.`. 

If you get this working, and it's a great idea, you should package it as a separate library on GitHub/PyPI. :smile:
