### ISSUE TITLE
Omit having all fieldnames present in json-file

### ISSUE THREAD

**Issue by magonser** [audreyr/cookiecutter#505]
Hi together,

Is there a way to have more fieldnames in the template than in the json-file with its default values? I could think of it being helpful if the CLI-interface just starts discovering, which fieldnames are present in the template and asks for possibly all of them when setting up a project, regardless if the fieldname is given in the json-file or not. I read through the docu, but haven't found anything on it. Please forgive me, if I missed out on something. I would appreciate a pointer in t he right direction. 

Thanks, M.

**Comment by pydanny** [comment]
Hi @magonser, Cookiecutter doesn't have any discovery feature like the one you want, and can't have it in the future. The reason for that it won't have this feature is that adding it would make the dynamic nature of the `cookiecutter.json` file impossible, which would break backwards capability.
