### ISSUE TITLE
Out of date Click dependency

### ISSUE THREAD

**Issue by reustonium** [audreyr/cookiecutter#512]
Click is up to version 5.1.  Should cookiecutter support the newer release of Click?

**Comment by pydanny** [comment]
Yes. It will be updated for the forthcoming 1.1 release.

**Comment by reustonium** [comment]
fantastic, I see there is a branch 'upgrade-click-to-4.0' that currently spec's
```python
'click<5.0'
```
just wanted to make sure that the 1.1 release specs
```python
'click <= 5.1'
```

Thanks!

**Comment by pydanny** [comment]
Done in 81ad3537a62656ce72b401bb9d7b3db1bd8cc893.
