### ISSUE TITLE
Appveyor integration unexpected result when python version is already installed

### ISSUE THREAD

**Issue by maiksensi** [audreyr/cookiecutter#518]
Hey, 

This issue will elaborate a bit on an inconvenience I noticed with the appveyor integration: If the enforced python major minor version is already installed, the installed version is used even though another patch version is wanted (say 2.7.9 is installed but 2.7.8 is wanted - the already installed version is used).

The way appveyor is setup it is supposed to install an explicit python version:

    environment:
        matrix:
            - PYTHON: "C:\\Python27"
              PYTHON_VERSION: "2.7.8"
              PYTHON_ARCH: "32"
              TOX_ENV: "py27"

but if the python directory already exists, nothing is installed. Instead the Installation is skipped: 

	Write-Host $python_home "already exists, skipped."

Currently the installed python 2.7 version on Appveyor machines is 2.7.9:
    
    # Version installed
    %PYTHON%/python -V
    Python 2.7.9
    # Version we actually want 
    ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
    C:\Python27 2.7.8 32

A fix would be to delete the existing installation before installing the enforced version and setting $PATH to the specific version, but I think that the appveyor scripts could be cleaned up instead. This is why I'd like to discuss an alternative approach before submitting a PR. 
Does cookiecutter need an explicit enforcement on a specific python version and architecture? 
Appveyor is constantly updating the patch and minor versions 2.7,x, 3.3.x, 3.4.x and 3.5.x in the future (32 Bit architecture). This is why I'd suggest to remove the explicit enforcement on patch versions and architecture (32 Bit is installed per default). 
To get an idea on how this would looks please check https://ci.appveyor.com/project/maiksensi/cookiecutter/build/1.0.73 and https://github.com/maiksensi/cookiecutter/blob/feat/appveyor-cleanup/appveyor.yml 
No matter what the outcome of this discussion is, I can supply a PR. 
Cheers.

**Comment by pydanny** [comment]
I like removing the explicit enforcement on patch versions. Can you submit a PR? Thanks! :smile:

**Comment by maiksensi** [comment]
Yeah sure. I'll get to it tomorrow.

**Comment by hackebrot** [comment]
Closing as we merged #523, thanks again :bow:
