### ISSUE TITLE
Support Python 3.5.0

### ISSUE THREAD

**Issue by maiksensi** [audreyr/cookiecutter#524]
Cookiecutter should support Python 3.5.0 (jippiie). I created a branch with the neccessary changes: 
https://github.com/maiksensi/cookiecutter/tree/feat/support-for-py35 
It already works with appveyor, as they recently updated their installations. Regarding Travis-CI, there is an open ticket at travis-ci/travis-ci#4794. There is a workaround but I guess it is not worth it. Instead, I will update this ticket as soon as they install py35 and create a PR.

**Comment by hackebrot** [comment]
Please see #522
