### ISSUE TITLE
brew install cookiecutter gives me an outdated version

### ISSUE THREAD

**Issue by kasperpeulen** [audreyr/cookiecutter#543]
I was installing cookiecutter using brew, but it seems like this is an outdated version.
Because of this, the docs didn't make sense to me. 

Would be great if this could get updated :)

see:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cookiecutter.rb

**Comment by hackebrot** [comment]
Thanks for pointing this out @kasperpeulen!

cc @michaeljoseph

**Comment by myyk** [comment]
+1

**Comment by hackebrot** [comment]
Done :smile_cat:
