### ISSUE TITLE
Add mention of PyCon US 2016 sponsorship to README

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#544]
This project is now an open source sponsor of PyCon US 2016: https://us.pycon.org/2016/sponsors/. We should include the PyCon US logo and more.

**Comment by hackebrot** [comment]
:+1: :+1:

**Comment by erichideki** [comment]
Where can I find a place to logo of Pycon US to add on README? And what text should we write?

**Comment by willingc** [comment]
Links:
https://us.pycon.org/2016/sponsors/
https://github.com/PyCon/pycon/blob/develop/pycon/static/img/SVG/PyCon16-logo.svg

**Comment by pydanny** [comment]
While we didn't put it in our README before the event, we can do it during the event!

**Comment by purplediane** [comment]
I'll work on this today.

**Comment by purplediane** [comment]
We can't figure out how to get the logo to display, but at least the verbiage is there.

**Comment by ivanlyon** [comment]
Using these 3 lines in the README.rst works for me (Indentation matters like Python, but I was unable to find a way to prevent the site from removing all leading whitespace hence the appearance of _4-spaces-indentation_):

----

`.. image:: https://raw.githubusercontent.com/PyCon/pycon/develop/pycon/static/img/PNG/PyCon16-logo.png`
_4-spaces-indentation_`:height: 128px`
_4-spaces-indentation_`:align: center`

**Comment by purplediane** [comment]
That works, but unfortunately it looks bad since the logo has transparent background. Mountain looks like the screen is dirty. :-(

**Comment by nonatomiclabs** [comment]
What about a screenshot of the PyCon website, with the blue background?

![pycon-logo](https://cloud.githubusercontent.com/assets/6297260/23959329/2f1e604c-09a5-11e7-968b-a5b51c9d948e.png)

**Comment by hackebrot** [comment]
I'm closing this now since @purplediane added a note in #720 and it's 2017 😛 

Thanks everyone 🍪
