### ISSUE TITLE
Define and use custom Jinja2 filters

### ISSUE THREAD

**Issue by chekunkov** [audreyr/cookiecutter#547]
Custom filters can make templating even more flexible. E.g. if I want to create nicely formatted .rst file in new project I should do something like this:

```
{% for _ in cookiecutter.project_name %}={% endfor %}
{{ cookiecutter.project_name }}
{% for _ in cookiecutter.project_name %}={% endfor %}
```

to produce

```
====================
My cool project name
====================
```

Looks cumbersome, right? How cool would it be to do something like this instead:

```
{{ cookiecutter.project_name|rst_h1 }}
```

Unfortunately there's no way to access Jinja2 environment before rendering a template - thus no way to add custom filters. 

I was thinking about following approach - add `filters` directory, where developer can place python modules with custom filters, import functions from those modules after environment instantiation and update `env.filters`. This should be simple to implement and if you give me a green light I'll submit a PR.

P.S. Actually I would love to have some way to access environment directly - then it would be unnecessary to do stuff described above. But I'm not sure how it could be implemented - maybe there could be some convention, like `environment.py` file in template root with `update_environment(env)` function... Seems clumsy, don't like this idea too much, so please share your thoughts.

**Comment by hackebrot** [comment]
Hi @chekunkov :wave: 

I like the idea of writing custom filters for **Cookiecutter**, yet I am not sure what would be the best way to integrate them. Having said that, I will definitely put some thought into it. 

On a side note: You could use [Jinja2's macros](http://jinja.pocoo.org/docs/dev/templates/#macros)  for the mentioned use case.

```
{%- macro rst_h1(text) -%}
{% for _ in text %}={% endfor %}
{{text}}
{% for _ in text %}={% endfor %}
{%- endmacro %}
```

```
{{ rst_h1('pytest-' + cookiecutter.plugin_name) }}
```

I created the a [branch](https://github.com/pytest-dev/cookiecutter-pytest-plugin/tree/template-macro-in-readme) that features a dedicated folder for macros, a hook that removes the folder after rendering the project and an import for the macros in a rst file.

```
{%- from "macros/rst" import doc_title, doc_subtitle -%}
```

**Comment by chekunkov** [comment]
Hi @hackebrot 

Yeah, macros can do the trick for the case I've mentioned, and helps to follow DRY, yet it's not as powerful and clean as plain Python, and I don't see any reason to hide this power from users :wink: 

BTW, instead of filters **Cookiecutter** can allow to register [Jinja2 extensions](http://jinja.pocoo.org/docs/dev/extensions/#module-jinja2.ext) which will give even more flexibility - anything up to defining custom tags. Possible implementation: `jinja_ext` package near `hooks` and `cookiecutter.json`, add it to path during template render and pass all underlying module path strings to `Environment` constructor.

Note on `environment.py` suggestion - it seems close to what `py.test` does with `conftest.py`

**Comment by hackebrot** [comment]
Filters :smile_cat: :+1: 

Extensions :worried: :-1: 

I feel the docs for [Writing Extensions](http://jinja.pocoo.org/docs/dev/extensions/#module-jinja2.ext) imply that this may get quite cumbersome for us to help users if they happen to run into named problems, sorry.

**Comment by audreyr** [comment]
I think it would be really nice to be able to use Jinja2 filters in extensions :+1: 

Rather than having a `filters/` directory, I think it would be better to specify a requirements file of filter packages (or other Python packages) to be installed before generation.

Keep thinking about ideas to access the environment directly too - if you can come up with something elegant that might work, I'd love to hear your ideas.

**Comment by shidarin** [comment]
Would also like to see filters being made available. A `filters/` folder would be nice for small utility filters where a full package would be overblown.

If you're doing package installs, you run into a whole bunch of pip requirements- can I specify a custom pypi server, version specifications, etc.

**Comment by hackebrot** [comment]
Think I may have something... :smirk_cat:

**Comment by xsteadfastx** [comment]
Any news on the filters? I use cookiecutter to create blog posts for pelican und want to use the slugish python package to create the slug from the title. Do I need to create a whole jinja2 extension for that? 

And BTW... Thanks for this great piece of software ☺

**Comment by hackebrot** [comment]
Thank you for your feedback @xsteadfastx! :bow: Appreciate it.

At this point you have to create a jinja2 extension that adds your filters to the environment.

**Comment by xsteadfastx** [comment]
ok... so i will google around how to write a extension for custom filters :) thank you.

**Comment by hackebrot** [comment]
No need for google, the [jinja2 docs](http://jinja.pocoo.org/docs/dev/extensions/#module-jinja2.ext) are just fine.

```python
# -*- coding: utf-8 -*-

from jinja2.ext import Extension


def slug(value):
    return value.lower().replace(' ', '-')


class BlogExtension(Extension):
    def __init__(self, environment):
        super(BlogExtension, self).__init__(environment)
        environment.filters['slug'] = slug
```

**Comment by xsteadfastx** [comment]
ok i will try that :) thanks a thousand times

**Comment by raykrueger** [comment]
Greetings from 2018! I'm having trouble understanding where I would put such a file? Is there a more complete example of how to add a jinja2 filter extension to an existing cookiecutter project?

**Comment by gsimon75** [comment]
I could accomplish this by defining a contextfilter:
```
env = Environment(...)

@contextfilter
def filter_apply(ctx, args, macro):
        return map(lambda x: ctx.call(macro, x), args)

env.filters['apply'] = filter_apply
```

And then in the template:
```
{% macro my_macro(x) -%}
{{ x ~ " again " ~ x }}
{%- endmacro %}

{{ some_list|apply(my_macro)|join(', ') }}
```

**Comment by con-f-use** [comment]
In 2020, I'd still like to see an `extensions/` or `filters/` directory similar to the `hooks/` directory, where I can load small custom extensions and filter from without the need to put something on the `PYTHONPATH` or install a package.

Or as my non-preferred alternative a `_requirements = ["jinja2-getenv-extension", "jinja2-getenv-extension"]` keyword for `cookiecutter.json` that would install the requirements (after the user is being prompted if they are okay with that).
