### ISSUE TITLE
Consider moving off PyYAML to ruamel.yaml

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#557]
PyYAML's current wheels do not appear to work for some Windows users. Specifically, they cause some Cookiecutter installations to fail. Also, there hasn't been a release endorsing use of Python 3.5. The PyYAML site hasn't seen an update in a long time.

On the other hand, https://pypi.python.org/pypi/ruamel.yaml is a fork/derivative of Kirill Simonov’s PyYAML. It appears to be working. We'll check on local Windows test machines to determine if it is a suitable replacement.

**Comment by hackebrot** [comment]
Resolved via #558 :+1:

**Comment by hackebrot** [comment]
Installation on Win 7 fails for [Cookiecutter 1.2.1](https://github.com/audreyr/cookiecutter/releases/tag/1.2.1) :worried:

**Comment by hackebrot** [comment]
It tries to install ``ruamel.yaml>=0.10.12``. :confused: 

See https://ci.appveyor.com/project/hackebrot/pytest-cookies/build/1.0.9/job/0m3dw868u1a7s79w

Breaks on local Win 7 box too.

Is it because the wheel is **universal** and somehow doesn't get that it is installed on win?

**Comment by pydanny** [comment]
This snippet was supposed to prevent PyYAML being installed on Windows machines installing it in a Python 2.7 environment: https://github.com/audreyr/cookiecutter/blob/master/setup.py#L38-L44

Clearly, it's working for some, but not all. Hand. Bang. Desk.

**Comment by pydanny** [comment]
I think I understand now: Because Cookiecutter is installed as a `Wheel` in modern `pip`, I think it's already been compiled. So while it works great off source, it fails in formal releases. :cry:

**Comment by hackebrot** [comment]
@audreyr @pydanny can you please explain why win7 requires special treatment? :bow: 

I set up **Cookiecutter v1.2.1** on another win box with x64 python and it worked just fine.

@ionelmc pointed out the according wheel is broken. I updated a issue in the [ruamel.yaml tracker](https://bitbucket.org/ruamel/yaml/issues/14/cant-install-ruamelyaml-package-under).

**Comment by ionelmc** [comment]
@pydanny use extras_require instead: https://wheel.readthedocs.org/en/latest/index.html?highlight=marker#defining-conditional-dependencies

**Comment by pydanny** [comment]
@ionelmc Thanks! We'll use that going forward

However, what we're facing is:

1. For better or worse, `PyYAML` is effectively unmaintained. It breaks on Windows using Python 3.5.
2. `raumel.yaml` works on on Windows using Python 3.5, but can apparently break on Windows using Python 2.7 and we've gotten a couple reports of issues on Mac OSX using Python 2.7.

What we're working on is making YAML optional, and using JSON as the fallback for `~/.cookiecutterrc`.

**Comment by frankwohuang** [comment]
under Ubuntu 15.10, using pyvenv created a virtual environment, then activate it, and pip install cookiecutter.

when run cookiecutter https://github.com/pydanny/cookiecutter-django.git command, get error message:
1>.  "Import Error: No module named 'click'" from cli.py line 15.
after pip install click 
2>. run the previous command, no click error but get another:
"Import Error: No module named 'ruamel'" from config.py line 20.
3>. tried to pip install ruamel or yaml, 
No distributions at all found for ruamel / yaml.

Sure it worked fine ten days ago under Ubuntu 14.04 environment with virtualenv where I used it created a project.

**Comment by pydanny** [comment]
Can I close this?

**Comment by hackebrot** [comment]
I think so @pydanny
