### ISSUE TITLE
Cookiecutter needs to always use utf-8 for writing files

### ISSUE THREAD

**Issue by ionelmc** [audreyr/cookiecutter#577]
I get this on Windows (pitty me):
```
  File "c:\program files\python 3.5\lib\site-packages\cookiecutter\generate.py", line 318, in generate_files
    run_hook('post_gen_project', project_dir, context)
  File "c:\program files\python 3.5\lib\site-packages\cookiecutter\hooks.py", line 107, in run_hook
    return run_script_with_context(script, project_dir, context)
  File "c:\program files\python 3.5\lib\site-packages\cookiecutter\hooks.py", line 90, in run_script_with_context
    temp.write(Template(contents).render(**context))
  File "c:\program files\python 3.5\lib\tempfile.py", line 482, in func_wrapper
    return func(*args, **kwargs)
  File "c:\program files\python 3.5\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0103' in position 1626: character maps to <undefined>
```

cookiecutter should pass `encoding='utf-8'` to `NamedTemporaryFile`

**Comment by hackebrot** [comment]
Unfortunately ``encoding`` is only supported in Python 3.

https://docs.python.org/3.5/library/tempfile.html#tempfile.NamedTemporaryFile

What's your recommendation?

**Comment by ionelmc** [comment]
Ugh ... version check and perhaps strong alcohol to wash out the dirty feeling? :grimacing:

**Comment by ionelmc** [comment]
On second thought, you might want to also have the encoding handling on py2. Hmmmmmm ...

**Comment by ionelmc** [comment]
I know! Something like `NamedTemporaryFile('rb').write(Template(contents).render(**context).encode('utf-8'))` - how about that?

**Comment by hackebrot** [comment]
Let's give it a try. Wanna submit a PR? :joy_cat:

**Comment by ionelmc** [comment]
If you promise to make a new cookiecutter release ... yesterday! :joy_cat:

**Comment by hackebrot** [comment]
Sure! Just send across a time machine, my friend :hourglass:

**Comment by ionelmc** [comment]
Not sure how that would help, mine only allows travel in the future. Here it is:

![pălincă](http://www.distileriilevalco.ro/poze/220949315_palinca_0,7_pear.jpg)
