### ISSUE TITLE
ignore jinja variables that dont begin with `cookiecutter`

### ISSUE THREAD

**Issue by scripter-co** [audreyr/cookiecutter#596]
As title says.

My cookiecutter repo has various ansible build scripts that use braces for various other items, currently cookiecutter just removes these variables.

**Comment by hackebrot** [comment]
Hi @scripter-co!

You can try to make use of [copy-without-render](http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render) if you require file-based exclusion.

HTH :bow:

**Comment by scripter-co** [comment]
I did look into this, but the problem is that I actually do want to render a file that has both `cookiecutter` variables and my variables for Ansible.

**Comment by hackebrot** [comment]
I see. :worried: 

Please feel free to submit a PR!

**Comment by pydanny** [comment]
Unless I'm misunderstanding the issue, this is exactly what Jinja2's "raw" tag is designed to address. Cookiecutter shouldn't have special functionality to address what Jinja2 already handles.

Closing this, but if I'm in error please reopen.

**Comment by pydanny** [comment]
This file demonstrates using Jinja2's `{% raw %}` tag in this capacity: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/templates/users/user_form.html

**Comment by scripter-co** [comment]
@pydanny No you're completely right.

**Comment by tamj0rd2** [comment]
That file doesn't exist @pydanny

**Comment by luzfcb** [comment]
@tamj0rd2 a folder was renamed. consequently the link to file has changed. 

The correct is:

https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/templates/users/user_form.html

**Comment by adamcunnington-mlg** [comment]
@pydanny I don't understand your response here - what if your template contains jinja references which **your application** renders, but which cookiecutter should not. E.g. cookiecutter should ignore them but I cannot make use of `{% raw %}` because in another context, jinja SHOULD render them.

Surely cookiecutter should not be attempting to substitute stuff that doesn't start with `cookiecutter.`

**Comment by adamcunnington-mlg** [comment]
Nevermind - solution is https://cookiecutter.readthedocs.io/en/latest/advanced/copy_without_render.html

**Comment by SodaDev** [comment]
> Nevermind - solution is https://cookiecutter.readthedocs.io/en/latest/advanced/copy_without_render.html

Just in case that someone will do into this thread. Nope it's not. Solution is using `{% raw %}` -> `{% endraw %}` for section of the file.

**Comment by geoffreyvanwyk** [comment]
Relevant Jinja documentation: https://jinja.palletsprojects.com/en/3.1.x/templates/#escaping
