### ISSUE TITLE
Tests that require git break on appveyor

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#599]
See #597, #598 :worried:

**Comment by hackebrot** [comment]
cc @maiksensi

**Comment by luzfcb** [comment]
@hackebrot this problem was expected?: https://ci.appveyor.com/project/audreyr/cookiecutter/build/1.0.806/job/mv3x1v5rjvi87kvp#L150

seems a bug in appveyor and mingw64 installation.

**Comment by hackebrot** [comment]
Nope :worried:

**Comment by maiksensi** [comment]
As I am not at home, I only had a brief look at it. You could try changing GIT's config by adding `http.sslverify false`. And try to verify whether this file exists `C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt` (`Get-ChildItem $DIRECTORY -force`). I am confident it is something with the `PATH` to the CABundle, depending on whether a new mingw64 was installed lately. I'll try to create a minimal example tomorrow and see if I can reproduce this.
