### ISSUE TITLE
Write docs on choice variables

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#600]
See #455

**Comment by maiksensi** [comment]
I suspect you already have an idea what they should cover. Can you outline what they should cover? So a fellow helper has a general idea what to write.

**Comment by hackebrot** [comment]
Hmm

* cookiecutter.json with choice value
* jinja2 conditional in template
* default value in rc
* example prompt

**Comment by hackebrot** [comment]
https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/hooks/post_gen_project.py#L12

**Comment by maiksensi** [comment]
Alright, I'll have a look at it :).

**Comment by hackebrot** [comment]
Cool! :smile: 

GitHub only allows Collaborators to be Assignees. Sorry about that.

**Comment by maiksensi** [comment]
Ah I thought this works on every account type, seems it only works for organizations.

**Comment by hackebrot** [comment]
See #611 :smile:
