### ISSUE TITLE
Drop distutils support

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#606]
I feel it's about time to drop **distutils** support as we rely on [extras_require of setuptools](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to handle **yaml** dependencies..

What's your opinion on this matter?

**Comment by hackebrot** [comment]
Also see #605

**Comment by pydanny** [comment]
:+1:

**Comment by audreyr** [comment]
Yeah, good point
