### ISSUE TITLE
cookiecutter does not work well in Python3.4

### ISSUE THREAD

**Issue by hongbinzuo** [audreyr/cookiecutter#619]
Hello,

I installed cookiecutter using the command `pip install cookiecutter` and it showed me success. But after I tried to run the command: `cookiecutter https://github.com/pydanny/cookiecutter-django`, it complained as below,
```
(env)root@8b95f2998ed1:# cookiecutter https://github.com/pydanny/cookiecutter-django
Traceback (most recent call last):
  File "/root/dmp/projects/tanzhen/env/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/root/dmp/projects/tanzhen/env/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/root/dmp/projects/tanzhen/env/lib/python3.4/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/root/dmp/projects/tanzhen/env/lib/python3.4/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
```
I checked the official documentation that tells me it supports Python3.4, could you please help on this?

My environement:
```
(env)root@8b95f2998ed1:# python
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
BTW, I used virtualenv.

**Comment by luzfcb** [comment]
please, run:

`pip freeze`

what is the output?

**Comment by luzfcb** [comment]
this seems to be another bug in `click`

**Comment by hongbinzuo** [comment]
The output of `pip freeze`:
(env)root@8b95f2998ed1:~/dmp/projects/tanzhen# pip freeze
binaryornot==0.4.0
chardet==2.3.0
click==6.2
cookiecutter==1.3.0
Django==1.9
future==0.15.2
Jinja2==2.8
MarkupSafe==0.23
mysql-connector-python==2.0.4
PyMySQL==0.6.7
ruamel.base==1.0.0
ruamel.yaml==0.10.12
wheel==0.24.0
whichcraft==0.1.1

**Comment by hongbinzuo** [comment]
Hi,

I found this post and the solution works fine for me: https://github.com/nvie/rq/issues/634

```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```

I think you can close this issue.

Thanks,
hongbin
