### ISSUE TITLE
Can i use my jinja environment on cookiecutter?

### ISSUE THREAD

**Issue by yufeiminds** [audreyr/cookiecutter#637]
I want to use some extra filters and global functions on my template. But the implement of `cookiecutter.generate.generate_files` create the environment inside of this function.

**Comment by hackebrot** [comment]
Hi @yufeiminds! :wave: 

The upcoming release of Cookiecutter let's you inject **jinja2 Extensions**.

See #617

**Comment by yufeiminds** [comment]
Thank you very much~! :+1:

**Comment by hackebrot** [comment]
Not at all. You're very much welcome :smile_cat:

**Comment by pgrzesik** [comment]
Is it possible to just set enviroment variable, without writing extensions ? I only need to set `trim_blocks` in environment.

**Comment by hackebrot** [comment]
@pgrzesik as of now, it's not possible to change the environments parameters.

**Comment by pgrzesik** [comment]
@hackebrot Thanks a lot!

**Comment by hackebrot** [comment]
@pgrzesik if you submit a PR that includes tests, I would be happy to review it for the next release.
