### ISSUE TITLE
cookiecutter-python is a dead link

### ISSUE THREAD

**Issue by prodicus** [audreyr/cookiecutter#651]
The cookiecutter template mentioned in README, named **cookiecutter-python** is a dead link.

**Comment by michaeljoseph** [comment]
@prodicus thanks for the issue :)
Do you think you could submit a quick PR for this?

**Comment by prodicus** [comment]
@michaeljoseph Sure why not! But I am not aware of the working link.

**Comment by michaeljoseph** [comment]
We can just remove it...

**Comment by prodicus** [comment]
@michaeljoseph On it :+1:
