### ISSUE TITLE
Cannot add angular tags to html files

### ISSUE THREAD

**Issue by matheuspoleza** [audreyr/cookiecutter#676]
## What happens:
Angular has DOM binds with `{{}}` tags. I have this html file:
![selection_388](https://cloud.githubusercontent.com/assets/8049914/14569949/26f88fc6-0318-11e6-93c4-bcc00ec92e17.png)

cookiecutter rise this error:
![selection_387](https://cloud.githubusercontent.com/assets/8049914/14569921/02135c72-0318-11e6-9c43-87e202861216.png)

## What should do:
- [ ] Just see to {{cookiecutter.propertie}} and not every {{ }} propertie

**Comment by luzfcb** [comment]
use Jinja2  `{% raw %}{% endraw %}` http://jinja.pocoo.org/docs/dev/templates/#escaping


```
{% raw %}{{angular-variable}}{% endraw %}
```

**Comment by matheuspoleza** [comment]
:+1:
