### ISSUE TITLE
insert .cookiecutterrc defaults even if they don't exist in cookiecutter.json

### ISSUE THREAD

**Issue by xesscorp** [audreyr/cookiecutter#679]
`apply_overwrites_to_context()` in cookiecutter 1.4 will skip variables in the .cookiecutterrc file if there is not a matching variable in the cookiecutter.json file. I would prefer it if the .cookiecutterrc variables were always inserted into the active context. That way I can have my global defaults for my name, organization and such in one place instead of having them spread around in multiple cookiecutter.json files.

However, the code specifically precludes this so I'm wondering if there is a valid reason why. But if it's an oversight, then maybe consider changing it so the global defaults are always inserted.

**Comment by hackebrot** [comment]
Hi @xesscorp!

We've had a very similar discussion in #597 and I'm still struggling to fully grasp the use case tbh.

#### Undefined Variables

Imagine you are a new user of Cookiecutter and have not created a template yourself. You find a template on the list that looks like a good choice for what you have in mind for your new project. You answer the question, as explained on the README, however you end up with a with an error like this one:

```
Unable to create file 'Makefile'
Error message: 'aws_s3_bucket_name' is undefined
```

This could be an effect of a template that **requires** to be invoked with a ``.cookiecutterrc`` that has ``default_context`` or that's used with via ``cookiecutter('foobar', extra_context={'name': 'Tyrion Lannister'}``.

This must be a horrible experience for new users and potentially stops them from using this project altogether. Which clearly not want we want.

#### Unwanted Prompting

If we populate the context with all of your default values even if they are not in ``cookiecutter.json``, you may be asked for input for variables which aren't used in the project. Unlike ``extra_context`` default values from the user rc file, are not passed in explicitly, so chances are you don't even realize that they will be prompted.

#### Global Defaults

As to your point:
> That way I can have my global defaults for my name, organization and such in one place instead of having them spread around in multiple cookiecutter.json files.

You can still do this in the current release. You will be prompted for them, but you can stick to your ``.cookiecutterrc`` values, if you want to. If that's a problem, you can change the template (I assume you use your own templates, as you've mentioned multiple ``cookiecutter.json`` files) to hide the variables from the user by prepending an underscore ``_organization``.

**Comment by xesscorp** [comment]
Thanks for the explanation. You're right, I had not considered the problem of sharing templates if some of the variables are only in a global file. I'll change my project cookiecutter.json files to explicitly mention the global defaults.

**Comment by mrburrito** [comment]
Here's a use case for loading the global variables in .cookiecutterrc that don't appear in cookiecutter.json.

I'm configuring a template for internal use that will, if requested, create the project in our internal GitLab. This requires the user's GitLab API Token. I want them to be able to include that in the `default_context` section without being prompted for it and, more importantly, without the token being exposed on the console. I can notify the user that they need to create that file and include the value in my pre/post processing scripts if it doesn't exist and they have chosen to create the remote repository.

There are workarounds -- I can require the token exist in a separate local file, external to cookiecutter, it just seemed to make sense to use the same variable system. Maybe not, the more I think about it.

Just some food for thought.

**Comment by hackebrot** [comment]
Hi @mrburrito 👋 

Any variable with a leading underscore ``_`` will not be prompted to the user.

Add ``"_gitlab_token": null`` to **cookiecutter.json**. Then add a sensible value in ``default_context`` to **.cookiecutterrc** and you should be fine w/o workarounds.

Hope this helps!
