### ISSUE TITLE
Starting a project

### ISSUE THREAD

**Issue by hjonasson** [audreyr/cookiecutter#681]
Hi all,

I am very excited about your project and hope to try it out. I installed it successfully with pip. I tried to both create a project on github and locally and neither worked.

Trying git gives

`subprocess.CalledProcessError: Command '[u'git', u'clone', u'https://github.com/hjonasson/cookiecutterglobal.git']' returned non-zero exit status 128`
(also tried without .git at the end which gave the same error)

Locally

`IOError: [Errno 2] No such file or directory: u'cookiecutterglobal/cookiecutter.json'`

Can somebody guide me in the right direction?

**Comment by pydanny** [comment]
https://github.com/hjonasson/cookiecutterglobal doesn't exist, hence why Cookiecutter is throwing an error. Create that repo, inclusive the right files, and it should work. :smile:

**Comment by michaeljoseph** [comment]
@hjonasson You need to either choose an [existing cookiecutter](http://cookiecutter.readthedocs.org/en/latest/readme.html#available-cookiecutters) or [create your own](http://cookiecutter.readthedocs.org/en/latest/tutorials.html#create-your-very-own-cookiecutter).
