### ISSUE TITLE
Only one directory copied by the cookiecutter

### ISSUE THREAD

**Issue by borismod** [audreyr/cookiecutter#683]
I've created my own template for cookiecutter. It contains three directories with project_name:
Here is my repo:
https://github.com/QualiSystems/cookiecutter-shellpackage

![image](https://cloud.githubusercontent.com/assets/209971/14850929/f6fca3f4-0c84-11e6-8219-4c6eeff8974f.png)

after executing cookiecutter on the repository, it created only single folder:

![image](https://cloud.githubusercontent.com/assets/209971/14850941/0f02a9f8-0c85-11e6-85fe-2fa363ae9e63.png)

Is there anything that I am doing wrong?
What documentation can you refer me to?

Thanks,
Boris

**Comment by michaeljoseph** [comment]
Hi @borismod,

We only support having a single templated root directory in your cookiecutter template.
So you'd need to move your `{{cookiecutter.project_name}}_*` directories into a single root directory:
```
cookiecutter-shellpackage/
└── {{cookiecutter.project_name}}
    └── {{cookiecutter.project_name}}_package
    └── {{cookiecutter.project_name}}_source
    └── {{cookiecutter.project_name}}_spec
```
