### ISSUE TITLE
Q: where to add Django+Ember CookieCutter

### ISSUE THREAD

**Issue by nanuxbe** [audreyr/cookiecutter#685]
Hello,

I'd like to make a PR with a couple cookiecutters I've made. One of them is for creating apps with Django and EmberJS (https://bitbucket.org/levit_scs/cc_django_ember_app) and I don't know in what section I should put it?
- Django
- JavaScript
- both
- a new section

And thanks for the great work!

**Comment by audreyr** [comment]
That's a good question. I'd say either the Django or JS section...whichever one you pick is up to you.

**Comment by nanuxbe** [comment]
Thanks
