### ISSUE TITLE
Use implicit codecov version?

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#691]
Cookiecutter uses @codecov to check and publish our coverage numbers. Right now we specify the version, which is fine. However, as it is not included in Cookiecutter's requirements, but as part of our test harness, it may be more expedient to define it without a version number. That way the @codecov team (@stevepeak, et al) can make changes to their API and client, and Cookiecutter just keeps moving along. 

This means we're doing less maintenance commits (2.0.2 to 2.0.3), but doesn't prevent us from spotting serious problems (like the PyYAML failure on Windows and AppVeyor that @hackebrot identified).

Note: PyYAML failing on @AppVeyor had nothing to do with @AppVeyor, rather it was caused by the somewhat unsupported nature of PyYAML in general.

**Comment by stevepeak** [comment]
Thanks @pydanny for brining up this discussion. I'll be happy to answer any questions that come up.

We did just deploy our new release and had couple bugs in the uploader that we solved. We will continue to improve the python uploader and add new features and improvements. Which is an advantage. Clearly the disadvantage is issues like this, though solved within 24 hours like they typically are.

Codecov welcomes all feedback, pull requests and suggestions 👍  Thank you

**Comment by michaeljoseph** [comment]
I'm 👍  on removing versions from _all_ our development dependencies.
I think the value of spotting issues and contributing to upstream bugs/issues outweighs the inconvenience of builds sometimes failing...

**Comment by hackebrot** [comment]
I believe almost all of our problems with CI resulted either from GitHub downtimes (caused by DDoS) or YAML. Either of these issues can be identified fairly quickly. 😁 

So I'm 👍 on not pinning test requirements. 

On a side note: Great work @stevepeak and team! Amazed by how fast you've rolled out a bugfix version after I posted on twitter.
