### ISSUE TITLE
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.

### ISSUE THREAD

**Issue by eromoe** [audreyr/cookiecutter#703]
env:
win 8.1 x64
python 2.7 x86
git-bash

I got this when running:(same error on git-bash/cmd)
```
$ cookiecutter https://github.com/sloria/cookiecutter-flask.git
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\cookiecutter\cli.py", line 106, in main
    config_file=user_config
  File "c:\python27\lib\site-packages\cookiecutter\main.py", line 107, in cookiecutter
    no_input=no_input
  File "c:\python27\lib\site-packages\cookiecutter\vcs.py", line 104, in clone
    raise VCSNotInstalled(msg)
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.
```

**Comment by michaeljoseph** [comment]
Hi @eromoe, are you able to run `git` from your command-line? You sounds like you don't have the `git` executable in your `$PATH`?

**Comment by eromoe** [comment]
I can run git from cmd and it is in my `$PATH`, even `git-bash(mingw64)` can not execute `cookiecutter https://github.com/sloria/cookiecutter-flask`.
I have to `git clone https://github.com/sloria/cookiecutter-flask`  then `cookiecutter  cookiecutter-flask`

**Comment by pydanny** [comment]
@eromoe, this is possibly an issue with Whichcraft, the library that powers the check your Windows machine is failing (https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/vcs.py#L74-L80). Is it possible for you to clone Whichcraft locally and run its tests?

If the tests fail, then it's something we can deal with in Whichcraft directly.

See https://github.com/pydanny/whichcraft

**Comment by eromoe** [comment]
E:\Project\whichcraft>python test_whichcraft.py
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: E:\Project\whichcraft, inifile:
plugins: cov-2.2.1
collected 2 items

test_whichcraft.py F.

================================== FAILURES ===================================
____________________________ test_existing_command ____________________________

    def test_existing_command():
        cmd = which('date')
>       assert cmd
E       assert None

test_whichcraft.py:9: AssertionError
===================== 1 failed, 1 passed in 0.17 seconds ======================

**Comment by michaeljoseph** [comment]
@eromoe, could you please raise this issue in the [whichcraft](https://github.com/pydanny/whichcraft) project?
Thanks for the investigation :)

**Comment by eromoe** [comment]
OK :)

**Comment by BrandenKeck** [comment]
Hi All,

I was having the same problem running from Command Prompt in Windows 8.
I discovered that I was able to run the cookie cutter command in the Git Bash shell and no longer experienced issues.

Hopefully this information is of help.

Best,
Branden

**Comment by Simran-IBM** [comment]
Same issue worked for me when I added path to cookiecutter.exe to Windows 10 environment variable.

**Comment by chaithra-91** [comment]
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed when i tried cookiecutter https://github.com/drivendata/cookiecutter-data-science in command prompt

**Comment by insspb** [comment]
@chaithra-91 this mean that you should install git in you system first. 
If you on windows use git bash, this is known issue on windows.

**Comment by Flauberth01** [comment]
Estou utilizando o Git Bash no Windows e solucionei o problema abrindo o terminal "GIT BASH" no VS code (editor que eu estava usando)

I'm using Git Bash on Windows and I solved the problem by opening the "GIT BASH" terminal in VS code (the editor I was using)

**Comment by JokyHub** [comment]
I added git to the Windows system path and it worked.
