### ISSUE TITLE
Improve calculation of Cookiecutter's reported coverage stats

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter#71]
1. The coverage stats from coveralls seem way off. For example, this is a readme change that incorrectly reports "Coverage decreased (-1.49%)": https://github.com/audreyr/cookiecutter/pull/70

   Things to try:
   * Instead of [coveralls](https://pypi.python.org/pypi/coveralls) (see [requirements/base_test.txt](https://github.com/audreyr/cookiecutter/blob/master/requirements/base_test.txt)), try [python-coveralls](https://pypi.python.org/pypi/python-coveralls/2.4.0)
   * Hunt down the bug in coveralls or python-coveralls if switching doesn't solve the problem.

2. The coverage stats from `make coverage` are different from those reported by coveralls. They're only calculated with the current active Python version.

   Try:
   * combine coverage reports from 2.6, 2.7, 3.3 into one with [the coverage combine command](http://nedbatchelder.com/code/coverage/cmd.html#cmd-combining)

**Comment by pydanny** [comment]
coveralls is providing broken images in GitHub. @michaeljoseph, why don't we just switch to codecov?

**Comment by michaeljoseph** [comment]
@pydanny :point_right: #369
