### ISSUE TITLE
Type Annotations with mypy

### ISSUE THREAD

**Issue by TylerLubeck** [audreyr/cookiecutter#712]
- Cookiecutter version: 1.4.0
- Template project url: n/a
- Python version: 3.5
- Operating System: OSX
### Description:

This is a working ticket to try out type annotations at the Pycon 2016 sprints

**Comment by hackebrot** [comment]
Hey @TylerLubeck! 👋 

Is it okay if we close this issue and look at the others instead?

**Comment by TylerLubeck** [comment]
Holy wow @hackebrot I had been checking the ticket periodically and just assumed y'all were busy. Never even crossed my mind to check here until I was clearing through some alerts.

Yeah, sure thing! Can I ask which "others" it is you're mentioning?

**Comment by hackebrot** [comment]
Hey @TylerLubeck! 👋 

Apologies for the late response. I was referring to #750 and #713, I think 🤔 

Closing this now. Thank you 😄
