### ISSUE TITLE
ASCII Encoding Assertion Error 

### ISSUE THREAD

**Issue by suledev** [audreyr/cookiecutter#717]
* Cookiecutter version: current
* Python version: 3.4.3
* Operating System: OSX

### Description:

Trying to run the test suite, ran into an issue with the test_cli.py  and test_cookiecutter_invocation.py scripts. Error produced in a VM with python 3.4.3. 

### What I've run:

```
    assert -1 == 2
E        +  where -1 = <Result RuntimeError('Click will abort further execution because Python 3 was configured to use ASCII as encoding for ...sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8',)>.exit_code

tests/test_cli.py:373: AssertionError



 assert 'Error: Missing argument "template".' in 'Traceback (most recent call last):\n  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py"... sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8\n'

tests/test_cookiecutter_invocation.py:25: AssertionError
```

Those weren't the only messages but the rest are more of the same, Assertion Error to do with ASCII encoding.

**Comment by hackebrot** [comment]
Hi @suledev! 👋 

Can you please make sure that the environment variables are set according to the [click docs](http://click.pocoo.org/5/python3/#python-3-surrogate-handling)?

**Comment by suledev** [comment]
Okay Thanks that was the error.

**Comment by hackebrot** [comment]
Np 😸
