### ISSUE TITLE
Recognize all contributors to cookiecutter at sprints

### ISSUE THREAD

**Issue by willingc** [audreyr/cookiecutter#719]
### Description:

Contributions at sprints span more than just GitHub commits. It takes many talents coming together to make a successful sprints. To recognize all of the individuals that contribute and do tasks like user testing, pairing, teaching, and more, add a document to the sphinx docs. Concept approved by @audreyr.

**Comment by phoebebauer** [comment]
I am working on this!

**Comment by hackebrot** [comment]
I've started to move my projects to **CONTRIBUTORS** rather than **AUTHORS** and try to also give credit for people who raise issues with valuable input. I definitely 👍 on this!
