### ISSUE TITLE
Tutorials issues

### ISSUE THREAD

**Issue by BruceEckel** [audreyr/cookiecutter#732]
Here: https://cookiecutter.readthedocs.io/en/latest/tutorials.html
Under the subhead:
### Create Your Very Own Cookiecutter
* Audrey's tutorial "Create a Cookiecutter From Scratch" stops after creating some directories and says "To be continued..." (Also says "Create a directory called {{ cookiecutter.repo_name }}" which might be out of date).
* Danny's article seems out of date and isn't really a tutorial. Should probably be unlinked.
* Hackbot's tutorials seem thorough but are too complex for beginners.

I'd like to see (and will try to work on):
1. Creating a "Hello, World"-style template: as minimal an example as possible, to get people over the initial hump.
2. Adding to the above in steps, or creating templates with intermediate complexity.
3. ... to the point where people are ready for Hackbot's tutorials.

**Comment by audreyr** [comment]
Yesterday @BruceEckel wrote https://github.com/BruceEckel/HelloCookieCutter1 which I'd like to turn into the official Cookiecutter tutorial. We've needed a minimal tutorial for a long time, and I think this is perfect.

The next step is to integrate https://github.com/BruceEckel/HelloCookieCutter1 into the Cookiecutter docs. This will require some thought about the best way to do this. Some TODOs:

* Get the link in https://github.com/audreyr/cookiecutter/blob/master/docs/tutorials.rst working properly
    * Does it make sense as a link to an external repo?
    * Or should we integrate it into the main docs as a git submodule or by bringing in the files?

* Add text to https://github.com/audreyr/cookiecutter/blob/master/docs/tutorials.rst to make the tutorial obvious as a starting point for people new to Cookiecutter

**Comment by dot2dotseurat** [comment]
Working on this :)

**Comment by hackebrot** [comment]
Great work @BruceEckel! 👍 

@audreyr I'm 👎 for git submodules - it makes things overly complicated. Prefer the other options 😄

**Comment by audreyr** [comment]
Thanks for the feedback @hackebrot!

Decided to stick with using a git submodule because it eases the burden of maintenance to have less in core, and because @BruceEckel offered to update the tutorial if any issues come up. 

@BruceEckel if you ever decide in the future that you don't want to maintain it anymore, let us know and we can bring the tutorial into core.
