### ISSUE TITLE
Split docs/advanced_usage.rst into several files

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter#744]
* Move each section from advanced_usage.rst into its own .rst file.
* Add each .rst file to docs/index.rst
* Build the docs locally to ensure that every doc shows up properly

**Comment by zzzirk** [comment]
Is there any preference as to filesystem layout or naming of these new files?

**Comment by audreyr** [comment]
No preferences, just do what you think makes the most sense. We can always change names later if needed.

I could see them either going directly into docs/ or into docs/advanced_usage/, but again no real preference here.

**Comment by michaeljoseph** [comment]
Closed via #749.
