### ISSUE TITLE
Injecting extra context from the CLI fails (--no-input)

### ISSUE THREAD

**Issue by kappataumu** [audreyr/cookiecutter#755]
* Cookiecutter version: Cookiecutter 1.4.0
* Template project url: https://github.com/msabramo/cookiecutter-supervisor
* Python version: 3.5.1
* Operating System: Ubuntu 14.04

### Description:

Injecting extra context from the CLI (when using `--no-input`) doesn't work (while `--no-input` on its own is fine). The error comes from [click](https://github.com/pallets/click), but I'm not sure if it is due to misconfiguration / possible bug or if injecting extra context from the CLI as a feature has been dropped?

### What I've run:

Using the example in the [README](https://github.com/audreyr/cookiecutter/blob/master/README.rst):
```
$ cookiecutter --no-input gh:msabramo/cookiecutter-supervisor program_name=foobar startsecs=10
Usage: cookiecutter [OPTIONS] TEMPLATE

Error: Got unexpected extra arguments (program_name=foobar startsecs=10)
```

Using `--no-input` on its own is OK:
```
$ cookiecutter --no-input https://github.com/pydanny/cookiecutter-django
Cloning into 'cookiecutter-django'...
remote: Counting objects: 6574, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 6574 (delta 43), reused 0 (delta 0), pack-reused 6494
Receiving objects: 100% (6574/6574), 2.63 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (4204/4204), done.
Checking connectivity... done.
You selected to use docker and a JS task runner. This is NOT supported out of the box for now. You can continue to use the project like you normally would, but you will need to add a js task runner service to your docker configuration manually.
```

**Comment by hackebrot** [comment]
Hi @kappataumu! 👋 

Cookiecutter 1.4.0 does not support extra context via CLI. It is planned to go live with [version 1.5.0](https://github.com/audreyr/cookiecutter/blob/master/HISTORY.rst#150-2016-04-20-).

You can install the development version via the following command (I recommend using a virtual environment for this):

``pip install git+https://github.com/audreyr/cookiecutter.git@master``

Hope this helps!

**Comment by kappataumu** [comment]
Sure does! Working great in 1.5.0, thanks.

**Comment by hackebrot** [comment]
You're most welcome! 🙇
