### ISSUE TITLE
Single quotes not escaped

### ISSUE THREAD

**Issue by shultz** [audreyr/cookiecutter#775]
* Cookiecutter version: Cookiecutter 1.4.0
* Template project url: https://github.com/pydanny/cookiecutter-django
* Python version: Python 3.4.3
* Operating System: Linux Mint 17.3

### Description:

Using a single quote (apostrophe) leads to a syntax error. Example is using cookiecutter-django with an apostrophe in the description field. It does not appear to be an issue with the template itself per https://github.com/pydanny/cookiecutter-django/issues/251

### What I've run:

```
dan@thinkpad ~/Code $ cookiecutter https://github.com/pydanny/cookiecutter-django
You've cloned /home/dan/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-clone it? [yes]: yes
Cloning into 'cookiecutter-django'...
remote: Counting objects: 6933, done.
remote: Total 6933 (delta 0), reused 0 (delta 0), pack-reused 6932
Receiving objects: 100% (6933/6933), 2.70 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (4463/4463), done.
Checking connectivity... done.
project_name [project_name]: test
project_slug [test]: test
author_name [Your Name]: Dan Shultz
email [Your email]: test@example.com
description [A short description of the project.]: Dan's Test Project
domain_name [example.com]: example.com
version [0.1.0]: 0.1.0
timezone [UTC]: America/Chicago
use_whitenoise [y]: y
use_celery [n]: n
use_mailhog [n]: n
use_sentry_for_error_reporting [y]: n
use_opbeat [n]: n
use_pycharm [n]: n
windows [n]: n
use_python2 [n]: n
use_docker [y]: y
use_heroku [n]: n
use_compressor [n]: n
Select js_task_runner:
1 - Gulp
2 - Grunt
3 - Webpack
4 - None
Choose from 1, 2, 3, 4 [1]: 4
use_lets_encrypt [n]: y
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 1
  File "/tmp/tmp9g6rdxac.py", line 181
    'description': 'Dan's Test Project',
                        ^
SyntaxError: invalid syntax
ERROR: Stopping generation because post_gen_project hook script didn't exit sucessfully
Hook script failed (exit status: 1)
```

**Comment by hackebrot** [comment]
Hi @shultz! 👋 

Thank you for opening an issue here. I can reproduce the issue causing a ``SyntaxError`` in the ``post_gen_project.py`` script for **cookiecutter-django**.

I'm not sure if it's a template's responsibility to take care of this or cookiecutter itself. That being said, a template could use a jinja2 filter to replace quotes in user input or we could escape by default, which might pose a problem to templates that already handle this.

😕

**Comment by shultz** [comment]
After some more troubleshooting and documentation reading, I don’t think this is an issue with cookiecutter itself.

To prove this to myself, I ran through the [Your First Cookiecutter](https://cookiecutter.readthedocs.io/en/latest/first_steps.html#your-first-cookiecutter) tutorial and I do not get an error when I use a single quote (apostrophe). 
```
$ cookiecutter HelloCookieCutter1/
directory_name [Hello]: Hello
file_name [Howdy]: Howdy
greeting_recipient [Dan]: O'Name

$ python3 Hello/Howdy.py 
Hello, O'Name!
```

I think the lies with cookiecutter-django in the post_gen_project.py file and I will be opening up an issue there.

Thanks!
