### ISSUE TITLE
Provide a __main__.py for the package

### ISSUE THREAD

**Issue by brettcannon** [audreyr/cookiecutter#787]
By providing a `__main__.py` file in the `cookiecutter` package it allows for `python.exe -m cookiecutter` to work (and the entry point can then simply point at the `__main__` module). I would be happy to provide a PR for this if you're amenable to the addition.

**Comment by hackebrot** [comment]
👍 from me

**Comment by pydanny** [comment]
👍

**Comment by brettcannon** [comment]
That's enough votes. :smile: . I'll see if I can get a PR created tomorrow.
