### ISSUE TITLE
missing wheel dependency

### ISSUE THREAD

**Issue by xrmx** [audreyr/cookiecutter#795]
* Cookiecutter version: 1.4.0
* Template project url:
* Python version: 3.5.2
* Operating System: debian sid

### Description:

Installing cookiecutter from a freshly created python 3.5 virtualenv fails for me. Installing *wheel* fixes the issue.

### What I've run:

```
$ pyvenv-3-5 venv35
$ . ./venv35/bin/activate
$ pip install cookiecutter
[...]
Building wheels for collected packages: click, future, chardet, arrow, MarkupSafe
  Running setup.py bdist_wheel for click ... error
  Complete output from command /home/rm/src/venv35/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tqrkfu4i/click/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpq0tsfvsapip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
```

**Comment by luzfcb** [comment]
@xrmx this seems to be a problem of `pip` or `setuptools`.

please, try updating `pip`, `setuptools` `wheel`

first, load the virtualenv and after, run

```bash
pip install pip setuptools wheel -U
```

and try again install cookiecutter

```bash
pip install cookiecutter -U
```

**Comment by xrmx** [comment]
The problem is that my virtualenv has pip but not wheel installed. And pip tries (wrongly?) to call the missing bdist_wheel when installing some requirements.

As written in the bug report installing wheel fixes the issue for me.

Said that *wheel* is not a requirement for pip's setup.py so we can't take it being there for granted. Since cookiecutter's  setup.py calls bdist_wheel itself in case of publish subcommand i think that adding wheel as requirement is the right thing to do though.

**Comment by luzfcb** [comment]
@xrmx apparently, `wheel` is required by `setuptools` https://github.com/pypa/setuptools/blob/master/setup.py#L187

I can not reproduce the error. 

In my machine, pyvenv-3.5 create a virtualenv with a very old version of pip and setuptools.

after you create and load a new virtualenv with pyvenv-3.5, what is the output of:

```bash
python -c "import setuptools,pip;print('setuptools',setuptools.__version__,'\npip',pip.__version__);"
```

**Comment by xrmx** [comment]
@luzfcb Here it is:
```
(fresh35) rm@rieux:~/src$ python -c "import setuptools,pip;print('setuptools',setuptools.__version__,'\npip',pip.__version__);"
setuptools 20.10.1 
pip 8.1.2
```

**Comment by xrmx** [comment]
Btw trying to debug with pypa people why my virtualenvs are borked.

@luzfcb I think we can close the bug, thanks for your help and sorry for the noise!
