### ISSUE TITLE
Can't pass variable/values on command line useing --no-input

### ISSUE THREAD

**Issue by dusktreader** [audreyr/cookiecutter#799]
* Cookiecutter version: 1.4.0
* Template project url: (unavailable -- private repo)
* Python version: 3.5
* Operating System: OSX

### Description:

I'm trying to pass cookiecutter variable values on the command line. It isn't working

### What I've run:

```
$ cookiecutter --no-input flask-api-template project_name="test-api"
Usage: cookiecutter [OPTIONS] TEMPLATE

Error: Got unexpected extra argument (project_name=test-api)
```

**Comment by hackebrot** [comment]
Hey @dusktreader! 👋 

#666 is not part of version 1.4.0. Can you please try again with the **master** branch?

Thanks! 🙇

**Comment by dusktreader** [comment]
@hackebrot discovered it was available in master shortly after posting this issue. Do you know when the next pypi release will br published?

**Comment by hackebrot** [comment]
We release version **1.5.0** a few weeks ago. 👍
