### ISSUE TITLE
Add cookiecutter to up-for-grabs

### ISSUE THREAD

**Issue by mariusavram91** [audreyr/cookiecutter#803]
What do you think about adding the project to [up-for-grabs](http://up-for-grabs.net/#/tags/python)? I see a few low-hanging-fruit issues there.

**Comment by michaeljoseph** [comment]
@mariusavram91 that sounds cool to me.
Would you like to add us?
I think the `please-help` and `low-hanging-fruit` tags would be appropriate.

**Comment by mariusavram91** [comment]
Happy to do it!

Thanks @michaeljoseph!

**Comment by michaeljoseph** [comment]
Thanks @mariusavram91!
