### ISSUE TITLE
Don't throw away user input when directory exists

### ISSUE THREAD

**Issue by mlabbe** [audreyr/cookiecutter#808]
- Cookiecutter version:1.4.0
- Template project url:any
- Python version:3.5.2
- Operating System:Windows 10
### Description:
1. Create a project by hitting enter a bunch
2. Create a project with the same output directory, but spend a LOT of time entering parameters
3. Observe as Cookiecutter throws away all of your answers because the output directory exists.

expected results:

Environment is validated before user is prompted for input, not after.

**Comment by hackebrot** [comment]
Cookiecutter does not know the target location for the new project before prompting.

You can try the [replay feature](http://cookiecutter.readthedocs.io/en/latest/advanced/replay.html) to re-use previously entered information.
