### ISSUE TITLE
Pretty Print JSON replays

### ISSUE THREAD

**Issue by mlabbe** [audreyr/cookiecutter#812]
* Cookiecutter version:1.4.0
* Template project url:all
* Python version:3.5.2
* Operating System:Windows 10

### Description:

It's useful to look at JSON replays to debug your template script. Currently they are generated without any whitespacing.

    json.dumps(indent=4, sort_keys=True)

**Comment by hackebrot** [comment]
Hi @mlabbe! 👋 

Thanks for raising this card.

The outlined behaviour is intentional though as the files are not meant to be human-readable but small in terms of size on disk.

If you want to have a more readable representation you can run

``$ python -m json.tool template.json``

or 

``$ cat template.json | jq`` (given that you have **jq** installed)

**Comment by mlabbe** [comment]
Hi, thanks for the reply.  Unfortunately, hard drive space makes no sense as a reason to WONTFIX this.  Modern operating systems have 4k disk block sizes. That means each file's actual storage size is rounded up to the next block size multiple. Adding a few bytes to a file does not increase its actual disk size unless it goes past a block boundary.  Pretty printing is, therefore, free.

Looking at my `.cookiecutter_replay` folder, I see every file as below 1KB.  The largest file is 837 bytes.  Let's estimate how much larger it would get it if the file was pretty printed with 4 spaces and a newline for every line:

    grep -o "," somefile.json |wc -l
    35

35 * (4+1) = 175

175 bytes does not put us close to a block boundary, or even make the file 1KB. Therefore, pretty printing is free.

However, manually pretty printing each regenerated replay takes up real programmer time.  Unless there is another way of partially replaying a run while debugging and adding template parameters, that's where we're at.

Just trying to make cookiecutter great.  Expect a pretty significant cookiecutter-based project generator from me, soon.

**Comment by mlabbe** [comment]
Hi @hackebrot , I know you marked as Wontfix, but do you have any additional comments on this since I raised the most recent point?

**Comment by hackebrot** [comment]
There is a workaround that only requires **Python** to generate a human-readable version from replay files. At the end this functionality is not user-facing, which I don't really see the point.

But I also understand that file size on disk is not a real concern. Can you create a PR, please?
