### ISSUE TITLE
Not escaped user input

### ISSUE THREAD

**Issue by lalstef** [audreyr/cookiecutter#813]
Supplying a string containing single quotes to the **description** field prompt resulted in a SyntaxError in the generated setup.py 

```python
setup(name=name,
    version=version,
    description='A 'test' description',
   ...
```

**Comment by michaeljoseph** [comment]
Hi @lalstef,

This looks like a dupe of #775, which was handled / fixed in the [cookiecutter template in question](https://github.com/pydanny/cookiecutter-django/issues/698)
