### ISSUE TITLE
# -*- coding: utf-8 -*- is not consistently used in all Python source files

### ISSUE THREAD

**Issue by ssteinerx** [audreyr/cookiecutter#814]
- Cookiecutter version:
  Cookiecutter 1.4.0
- Template project url:
  none
- Python version:
  3.5
- Operating System:
  OS X
  ### Description:
  # -_\- coding: utf-8 -_\- is not consistently used in all Python source files
### What I've run:

Nothing, it's an observation of an inconsistency in the project.

**Comment by hackebrot** [comment]
Hi @ssteinerx! 👋 

Good catch - mind to submit a PR adding missing encoding declarations?

**Comment by andytom** [comment]
Hi @ssteinerx and @hackebrot,

I've opened a PR (#852) for this. Hope you don't mind.

**Comment by ssteinerx** [comment]
Not at all -- thanks for getting to this!

S
aka/ssteinerX
