### ISSUE TITLE
Restart cookiecutter on error from hooks

### ISSUE THREAD

**Issue by ambross** [audreyr/cookiecutter#819]
In my cookiecutter template I have set few verification (like naming convention) rules in hooks ( pre_gen_project.py / post_gen_project.py) . So , when these verification failed during cookiecutter project creation, cookiecutter exit without creating project. 

I would like to re initiate cookiecutter from hooks. Is it possible?

**Comment by hackebrot** [comment]
You can re-use previously entered information using the [replay feature](http://cookiecutter.readthedocs.io/en/latest/advanced/replay.html). Hope this helps!
