### ISSUE TITLE
Custom context template holder name

### ISSUE THREAD

**Issue by urosjarc** [audreyr/cookiecutter#822]
Currently you can't replace `{{coockiecutter.something}}` with some shorter version like
`{{cc.something}}`... [see the link...](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/main.py#L80)

I would really like to discuss how to implement this feature to the coockiecutter, I can make pull requests to make this happend.

**Comment by hackebrot** [comment]
Maybe you can add a comment to the discussion on #380?

**Comment by urosjarc** [comment]
@hackebrot : I change my focus to yeoman generator.

**Comment by hackebrot** [comment]
Okay, fair enough! ☺️ I'm closing as a duple of #380 then.
