### ISSUE TITLE
Recommended way to generate one file only from a folder

### ISSUE THREAD

**Issue by bittner** [audreyr/cookiecutter#823]
* Cookiecutter version: _latest_
* Template project url:  _none yet_
* Python version: _any_ (3.5 atm)
* Operating System: _Ubuntu Linux 16.04_

### Description:

I'm trying to generate alternative configuration files for a project based on user input (e.g. Travis CI _or_ Codeship _or_ GitLab build configuration, MIT _or_ Apache 2.0 _or_ ... license, etc.).

### What I've run:

One simple way to implement this would be:

- Create a file `{{ cookiecutter.build_server }}`, and
- Have an `{% if cookiecutter.build_server == '.travis-ci.yml' %}...{% endif %}` section for each possible choice in there.

Is this the only way? This does become clumsy over time, I feel.

### Possible alternative?

I've thought about a more elegant way to do stuff. It could be something like:

- Having a folder `{{ cookiecutter.build_server }}`, and
- in that folder all files representing the possible choices (e.g. `.travis.yml`, `codeship.yml`, `gitlab-ci.yml`, etc.).
- The result of a `cookiecutter` run would be a file according to the related choice where the folder is placed in the template.

Is this something that can be easily done with `cookiecutter`? Maybe with some `pre_gen` or `post_gen` hook?

Is there a better way, a more elegant one?

**Comment by hackebrot** [comment]
Hi @bittner! 👋 

I use a folder and a post-gen hook:

- [templated file](https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/pytest-%7B%7Bcookiecutter.plugin_name%7D%7D/LICENSE)
- [options](https://github.com/pytest-dev/cookiecutter-pytest-plugin/tree/master/pytest-%7B%7Bcookiecutter.plugin_name%7D%7D/licenses)
- [post-gen hook](https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/hooks/post_gen_project.py#L33)

Hope this helps! 😄

**Comment by bittner** [comment]
That looks good, thank you! :+1: 

There is probably no (easy) way to avoid creating the files in the first place (i.e. "ignore folder") instead of deleting them in the end, right? - Just for the case I allow writing over an existing, potentially modified, project.
