### ISSUE TITLE
Unclear README instructions on how to use an already cloned cookiecutter

### ISSUE THREAD

**Issue by kevgathuku** [audreyr/cookiecutter#835]
* Cookiecutter version: 1.4.0 
* Template project url: https://github.com/audreyr/cookiecutter-pypackage
* Python version: Python 3.5.2
* Operating System: Mac OS

### Description:
I have already run ` cookiecutter gh:audreyr/cookiecutter-pypackage` and it fetched the repo correctly in to my `~/.cookiecutters/`.
However I got a detail wrong during the prompts and had to rerun `cookiecutter` to generate a new package.
I have the `cookiecutter-pypackage` already in my `~/.cookiecutters/` and I was expecting the following instructions to work if I want to re-create a new cookiecutter package.
> According to the [README](https://github.com/audreyr/cookiecutter/blob/master/README.rst):
> If you have already cloned a cookiecutter into ~/.cookiecutters/, you can reference it by directory name:
```
# Clone cookiecutter-pypackage
$ cookiecutter gh:audreyr/cookiecutter-pypackage
# Now you can use the already cloned cookiecutter by name
$ cookiecutter cookiecutter-pypackage
```

### What I've run:
`cookiecutter cookiecutter-pypackage` as pointed out in the README, but that does not work.
The docs are not explicit that I have to run the command with the path where the cookiecutter has been cloned.
The command that has worked for me is:
`cookiecutter ~/.cookiecutters/cookiecutter-pypackage`

```
$ cookiecutter cookiecutter-pypackage
The repository cookiecutter-pypackage could not be located.
```

**Comment by hackebrot** [comment]
Hi @kevgathuku! 👋 

I assume you are running the latest version from PyPI? The feature to support referencing local templates by name, #825, was merged a couple of days ago and **has not been released just yet**.

Which means the docs are in fact correct for the current master branch.

```no-highlight
$ pip install git+https://github.com/audreyr/cookiecutter
```

You can always checkout the docs for the version that you are running by selecting the version tag via the GitHub file browser

https://github.com/audreyr/cookiecutter/tree/1.4.0

Hope this helps!

**Comment by kevgathuku** [comment]
Nice! I wasn't aware of this. It works perfectly with the latest master from GitHub.
Thanks a lot for the help @hackebrot

**Comment by hackebrot** [comment]
You're most welcome @kevgathuku 👍
