### ISSUE TITLE
Unable to use cookiecutter with the py launcher on Windows

### ISSUE THREAD

**Issue by ivanz** [audreyr/cookiecutter#841]
I am unable to use cookiecutter with Python for Windows using the built-in [py launcher](https://docs.python.org/3/using/windows.html#launcher):

```
C:\Users\ivanzlatev>py -3 -m pip install cookiecutter
Requirement already satisfied (use --upgrade to upgrade): cookiecutter in c:\users\ivanzlatev\appdata\local\programs\python\python35-32\lib\site-packages
<..snip..>

C:\Users\ivanzlatev>py -3 -m cookiecutter
C:\Users\ivanzlatev\AppData\Local\Programs\Python\Python35-32\python.exe: No module named cookiecutter.__main__; 'cookiecutter' is a package and cannot be directly executed
```

**Comment by luzfcb** [comment]
@ivanz the pull-request https://github.com/audreyr/cookiecutter/pull/788 include this feature, but will be release only in the next version of cookiecutter (1.5.0)

**Comment by hackebrot** [comment]
We release **cookiecutter 1.5.0** a few weeks ago! 👍
