### ISSUE TITLE
Docs: remove [sudo] from Installation, add pre-reqs and packaging tools reference

### ISSUE THREAD

**Issue by stevepiercy** [audreyr/cookiecutter#869]
* Cookiecutter version: master
* Template project url: n/a
* Python version: n/a
* Operating System: n/a

### Description:

In the [installation instructions](https://cookiecutter.readthedocs.io/en/latest/installation.html), there are an optional `[sudo]`s, which implies installing cookiecutter into a system Python instead of a virtual environment.

In Pyramid, we do more user hand-holding, starting from installing Python, then satisfying [Requirements for Installing Packages](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html#requirements-for-installing-packages), and finally creating a virtual environment into which we install Pyramid for either [UNIX](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html#installing-pyramid-on-a-unix-system) or [Windows](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html#installing-pyramid-on-a-windows-system).

Would cookiecutter maintainers be interested in an approach similar to Pyramid's? I would submit the PR, if amenable.

### What I've run:

n/a

**Comment by hackebrot** [comment]
Hey @stevepiercy! 👋 

I think that's a great idea. Would love to review a PR.

**Comment by mmerickel** [comment]
FWIW ``pip install --user cookiecutter`` and a note about ensuring that the relevant bin folder ``$HOME/.local/bin`` (not sure what it is on windows) is on your path is much closer to a best practice these days than anything else involving pip installing a system-wide tool.

**Comment by stevepiercy** [comment]
From pip's help:

>  --user                      Install to the Python user install directory for your platform. Typically ~/.local/, or %APPDATA%\Python on Windows. (See the Python documentation for [site.USER_BASE](https://docs.python.org/3/library/site.html#site.USER_BASE) for full details.)

@hackebrot I have some docs to finish up in Pyramid first, then I'll return to this issue.

**Comment by stevepiercy** [comment]
@hackebrot see #880

**Comment by stevepiercy** [comment]
Closed by merging #880
