### ISSUE TITLE
Look into using a subprocess backport in the future

### ISSUE THREAD

**Issue by audreyr** [audreyr/cookiecutter#88]
I'm removing the `subprocess32` package (backport of subprocess) from the Cookiecutter dependencies, since I had trouble installing it on Windows and think it would cause installation issues for Windows users.

Specifically, I couldn't get it to build with MinGW. (I'm a bit rusty with Windows and MinGW, so this could be my fault.)

TODO: look into it more and report details as per https://code.google.com/p/python-subprocess32/ when I get a chance.

At some point, it would be nice to look into using `subprocess32` or similar again. For now, it's not critical to 0.7.0, so it can be removed.

**Comment by pydanny** [comment]
Since we've removed support for Python 2.6 for the upcoming 1.0 release (#201), I'm closing this issue.
