### ISSUE TITLE
Accepting default dict parameter value with no user input causes string "default" to be put into dict parameter

### ISSUE THREAD

**Issue by e-kolpakov** [audreyr/cookiecutter#882]
* Cookiecutter version: 1.5
* Template project url: private repo, minimal example is attached
* Python version: 2.7.10
* Operating System: Mac OS X 10.10.5

### Description:

I'm using dict parameter and trying to let it use default value. When prompted, `[default]` is shown as dict parameter default value. Then, if I respond to prompt with:

1. Just enter (i.e. no user input) - project cutting fails due to an error, as cookiecutter puts `default` into dict parameter (i.e. it becomes string instead of dict).
2. String "default" and enter - project is cooked successfully with default value.

In two words, just accepting default value for dict parameter by providing no user input causes string "default" to be put into a dict parameter instead of default value provided in cookiecutter.json.

If you allow some speculation, this happens because `click.prompt` [does not call `value_proc` if no user input is given](https://github.com/pallets/click/blob/master/click/termui.py#L103-L104)

See console session logs below.

### What I've run:

Failure:
```
cookiecutter minimal-example/
app_name [dict_default_bug]: 
dict [default]: 
Unable to create file 'placeholder.md'
Error message: 'str object' has no attribute 'foo'
Context: {
    "cookiecutter": {
        "app_name": "dict_default_bug", 
        "dict": "default"
    }
}
```

Success:
```
cookiecutter minimal-example/
app_name [dict_default_bug]: 
dict [default]: default
```
[minimal-example.zip](https://github.com/audreyr/cookiecutter/files/686416/minimal-example.zip)

**Comment by hackebrot** [comment]
Hi @e-kolpakov! 👋 

Thank you for this detailed bug report. It helped me implement a fix in no time.

Can you please try out #884?
