### ISSUE TITLE
tempfiles aren't removed

### ISSUE THREAD

**Issue by cheungnj** [audreyr/cookiecutter#886]
After cleaning my `/tmp` directory, then running cookiecutter several times, it appears as though the temp files from [run_script_with_context](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/hooks.py#L115) aren't removed. Is this intended behavior?

**Comment by michaeljoseph** [comment]
Hi @cheungnj 👋 

Many applications leave files in the `/tmp` directory- I don't think there's anything to be gained from `cookiecutter` deleting them.

**Comment by hackebrot** [comment]
The OS will clean up the files eventually IIRC.
