### ISSUE TITLE
Have optional files/folder

### ISSUE THREAD

**Issue by glassresistor** [audreyr/cookiecutter#897]
* Cookiecutter version: All
* Template project url: None
* Python version: All
* Operating System: All

### Description:

Since cookiecutter uses Jinja2 for generating file names it should be possible to have optional files/folders with a syntax for example having a folder named `{% if cookiecutter.include_extra %}extra{% endif %}` would only make the folder and its contents if incldue_extra is Truef

Is there any interest in doing this?

**Comment by pydanny** [comment]
This feature already works with Cookiecutter. It doesn't workork on Windows because of the limitative of their file system.
