### ISSUE TITLE
Replay doesn't apply Choice Variables

### ISSUE THREAD

**Issue by mjlyons** [audreyr/cookiecutter#898]
* Cookiecutter version: 1.5.0
* Template project url: private repo, but I can make an example if it helps
* Python version: 3.6.0
* Operating System: MacOS 10.12.3

### Description:

I'm trying to apply a replay file to a cookiecutter template that uses a [Choice Variable](http://cookiecutter.readthedocs.io/en/latest/advanced/choice_variables.html). The value of the Choice Variable is correctly recorded in the replay file after templating, but the choice variable value is ignored if passed in via extra_content.

### What I've run:

I use a custom script utilizing the API rather than the CLI. I can provide an example if it helps (copy and paste won't add much context)

**Comment by mjlyons** [comment]
Sorry, my mistake -- I misunderstood how choice variables are applied (thought it would remember the index, instead changes the order). Sorry to bother you, thanks for the great tool!

**Comment by jmdacruz** [comment]
@mjlyons Did you manage to override a choice variable using `extra_context`? I'm also using the API rather than the CLI, and I have a use case in which I want to populate the list of choices dynamically.

**Comment by mjlyons** [comment]
@jmdacruz Sorry about the absurdly late reply, lost access to my personal development machine and had to get another. Yes this does work for me, the thing that tripped me up is that cookiecutter changes the order of choices (to always make the default the first, I believe). Is this working for you now?

**Comment by jmdacruz** [comment]
No worries @mjlyons! Yes, this is now working for me too.
