### ISSUE TITLE
Add current date

### ISSUE THREAD

**Issue by artemnovichkov** [audreyr/cookiecutter#902]
How to add current date as option?

**Comment by hackebrot** [comment]
Hi @artemnovichkov! 👋 

You can insert the current date and time using [jinja2-time](https://github.com/hackebrot/jinja2-time), which comes with cookiecutter.

```
{% now 'utc', '%Y' %}
```

Check out this [example](https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/pytest-%7B%7Bcookiecutter.plugin_name%7D%7D/licenses/MIT#L4).

**Comment by artemnovichkov** [comment]
@hackebrot, thank you! I used `{% now 'local', '%d/%m/%Y' %}` for similar date format.
