### ISSUE TITLE
Post-creation hook does not run

### ISSUE THREAD

**Issue by sr-murthy** [audreyr/cookiecutter#918]
* Cookiecutter version: 1.5.1
* Template project url: private Git repository
* Python version: 2.7.10
* Operating System: OS X 10.10.5, Ubuntu 16.04 LTS

### Description:

// REPLACE ME: I've added a `hooks/post_gen_hook.py`, which is an executable Python 2.7 script, to the project slug directory in the source repo and run cookiecutter but this hook does not run. The hook creates a Git repo inside the replicated project and adds Git submodules inside one of the project subfolders.

### What I've run:

```
cookiecutter <source GitHub repo>
```

**Comment by hackebrot** [comment]
Hi @sr-murthy! 👋 

Your Python script needs to be renamed to ``hooks/post_gen_project.py``.

Find out more in the [hooks documentation](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html).

I'm closing this issue for now. Please get in touch if this doesn't work.

**Comment by sr-murthy** [comment]
Thanks, it works.
