### ISSUE TITLE
brew install installs an old version

### ISSUE THREAD

**Issue by wrrrrn** [audreyr/cookiecutter#919]
* Cookiecutter version: cookiecutter-1.4.0
* Template project url:
* Python version:
* Operating System: OSX 10.11.2

### Description:

brew currently installs 1.4.0, the latest is 1.5.1

### What I've run:

```
brew install cookiecutter
```

**Comment by hackebrot** [comment]
Hi @wrrrrn! 👋 

Can you please run ``$ brew update`` and try again?

```bash
$ brew info cookiecutter
cookiecutter: stable 1.5.1 (bottled), HEAD
```

**Comment by wrrrrn** [comment]
Sorted! Thanks for the snappy response @hackebrot

**Comment by hackebrot** [comment]
Cool! Have a good one 🍪
