### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by harilalpatel** [audreyr/cookiecutter#924]
* Cookiecutter version:
* Template project url:
* Python version:
* Operating System:

### Description:

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### What I've run:

```
// REPLACE ME: Paste a log of command(s) you ran and cookiecutter's output, tracebacks, etc, here
```

**Comment by hackebrot** [comment]
Hi @harilalpatel! 👋 

It worked - you successfully created an issue. 👍 

I'm closing this but, but feel free to comment if you have questions regarding cookiecutter.
