### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by eyalev** [audreyr/cookiecutter#937]
https://github.com/audreyr/cookiecutter/blob/master/docs/advanced/copy_without_render.rst

> To avoid rendering directories and files of a cookiecutter **mould**

**Comment by eyalev** [comment]
I suggest to remove 'mould'
PR: https://github.com/audreyr/cookiecutter/pull/938

**Comment by hackebrot** [comment]
Thanks 😄 I merged #938 earlier.
