### ISSUE TITLE
Explain how cookiecutter finds template directory

### ISSUE THREAD

**Issue by njvack** [audreyr/cookiecutter#942]
I'm trying to learn cookiecutter, and in the tutorials and such, it doesn't explain how it chooses a template directory. It's just kind of magic that it somehow knows to look for ```{{cookiecutter.project_slug}}``` or any of a variety of other values that are used in other cookiecutter examples.

Source-diving led me to `find.py` and `find_template()` which suggest that it's the first jinja-like thing with "cookiecutter" in the directory name. Which is cool; however, it would be super helpful to make that explicit in the tutorial.

Thanks for the sweet project!

**Comment by hackebrot** [comment]
Hi @njvack! 👋 

That's a very good point. Thank you for the suggestion and the feedback, happy to hear that you like cookiecutter. 😊
