### ISSUE TITLE
Feature Request: Julia

### ISSUE THREAD

**Issue by roryhr** [audreyr/cookiecutter#953]
I've been around Julia long enough to want to make a package but not long enough to know the best practices so a template would be really helpful.

**Comment by hackebrot** [comment]
Hey @roryhr! 👋 

Although there are [a few cookiecutter templates](https://github.com/audreyr/cookiecutter#cookiecutter-specials) that the cookiecutter core team maintains, this is the wrong place for this. The [templates listed on our README](https://github.com/audreyr/cookiecutter#a-pantry-full-of-cookiecutters) are being developed by the wider community and live outside this project.

Let me forward your question to our [Gitter chat](https://gitter.im/audreyr/cookiecutter) and see if anyone has any pointers. You're very welcome to join the chat, if you want do! 👍
