### ISSUE TITLE
dev.yml error with gulp, doesn't seem to be installed in image

### ISSUE THREAD

**Issue by japrogramer** [audreyr/cookiecutter#962]
* Cookiecutter version: 1.5.1
* Template project url:
* Python version: 3.6.1
* Operating System: Linux The_Black_Knight 4.11.5-1-ARCH #1 SMP PREEMPT Wed Jun 14 16:19:27 CEST 2017 x86_64 GNU/Linux

### Description:

I am trying to get the dev.yml build to get up

### What I've run:
$docker-compose -f dev.yml build
$docker-compose -f dev.yml up
```
Creating network "aqua_default" with the default driver
Creating aqua_node_1 ...
Creating aqua_postgres_1 ...
Creating aqua_node_1
Creating aqua_node_1 ... error

ERROR: for aqua_node_1  Cannot start service node: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"gulp\\": executable file not found in $PATH"'

ERROR: for node  Cannot start service node: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"gulp\\": executable file not found in $PATH"'
ERROR: Encountered errors while bringing up the project.
```

**Comment by hackebrot** [comment]
Hey @japrogramer! 👋 

Cookiecutter generates projects based on templates and does not control what is installed in your Docker image. This sounds like there is an issue with a missing dependency in the template. Can you please raise this issue with the template project?

Thank you!

**Comment by japrogramer** [comment]
https://github.com/pydanny/cookiecutter-django
This is the template url that i used. for whatever reason i didn't set it initially in my bug report.
Im going to open an issue with them too.
