### ISSUE TITLE
Cookiecutter-a-valid-repository-for-x-could-not-be-found-in-the-following-locat

### ISSUE THREAD

**Issue by kc1** [audreyr/cookiecutter#965]
* Cookiecutter version: Cookiecutter 1.5.1 
* Template project url:
* Python version: 2.7.13
* Operating System: win 10

https://stackoverflow.com/questions/44834547/cookiecutter-a-valid-repository-for-x-could-not-be-found-in-the-following-locat

**Comment by luzfcb** [comment]
You even created the template and want to generate a new spider using it?
if yes, please, upload you cookiecutter template to github and send the url of repository.


Cookiecutter expect that the target path contains a cookiecuter.json file on root of path

Cookiecutter does not run your spider.

**Comment by kc1** [comment]
Still does not work with remote repo on bitbucket : https://stackoverflow.com/questions/44851579/cookiecutter-a-valid-repository-not-found-with-cloning-remote-repo

**Comment by pydanny** [comment]
Can you:

* share your repo
* Paste the error message here

These are needed to diagnose your problem.

**Comment by kc1** [comment]
https://github.com/kc1/ccspider is repo

$ cookiecutter https://github.com/kc1/ccspider
	A valid repository for "https://github.com/kc1/ccspider" could not be found in the following locations:
	c:\Users\ExamPle\.cookiecutters\ccspider

**Comment by pydanny** [comment]
Rename the `cookiecutter` file to `cookiecutter.json`

**Comment by kc1** [comment]
Thank you!
