### ISSUE TITLE
gh: prefix doesn't work anymore

### ISSUE THREAD

**Issue by noirbizarre** [audreyr/cookiecutter#966]
* Cookiecutter version: 1.5.1
* Template project url: `gh:*`
* Python version: 2.7.13
* Operating System: Linux

### Description:

cookiecutter does not honor prefixes anymore.

### What I've run:

Simply testing the example from the README doesn't work as expected:

``` bash
$ cookiecutter gh:audreyr/cookiecutter-pypackage
A valid repository for "gh:audreyr/cookiecutter-pypackage" could not be found in the following locations:
gh:audreyr/cookiecutter-pypackage
/home/me/.cookiecutters/gh:audreyr/cookiecutter-pypackage
```
The same commands using the full repository path works as expected:

```bash
$ cookiecutter https://github.com/audreyr/cookiecutter-pypackage
```

**Comment by hackebrot** [comment]
Hi @noirbizarre! 👋 

Thank you for pointing this out. I noticed this too and have done some work to address this, but don't have the time wrap up my PR at the moment.

You probably have ``abbreviations`` in your ``~/.cookiecutterrc``, right? The current implementation overwrites config keys, which means it discards the default values if you have any ``abbreviations`` in your user config.

**Comment by hackebrot** [comment]
Hey @noirbizarre, can you please review and/or try out #967?

**Comment by noirbizarre** [comment]
Yes, you're right, I had abbreviations in my `~/.cookiecutterrc`.
I reviewed your PR :+1:
