### ISSUE TITLE
Maintain Code coverage to 100%

### ISSUE THREAD

**Issue by theodesp** [audreyr/cookiecutter#978]
* Cookiecutter version: latest
* Template project url:
* Python version: 3..6
* Operating System: Macos

### Description:
Code coverage is 94%. The following 2 lines of code are not tested based on the latest coverage report.

> cookiecutter/htmlcov/cookiecutter_utils_py.html
![screen shot 2017-08-14 at 11 13 47](https://user-images.githubusercontent.com/328805/29267753-fc072fc2-80e1-11e7-9390-9485d43427ca.png)

### What I've run:

```
make coverage
```

We need to perform additional test for this

**Comment by michaeljoseph** [comment]
Hi @theodesp,

Those lines are covered by appveyor / windows test runs: https://ci.appveyor.com/project/audreyr/cookiecutter/build/1.0.1605/job/r1w53jswcoemgw7j#L140

Good looking out though 🍪
