### ISSUE TITLE
Don't assume Bitbucket repositories are Mercurial repos

### ISSUE THREAD

**Issue by jboynyc** [audreyr/cookiecutter#987]
* Cookiecutter version: 1.5.1
* Python version: 3.6
* Operating System: Arch Linux

### Description:

I'm trying to use a template hosted in a git repository on Bitbucket. Supplying the template repository URL results in an error because cookiecutter attempts to clone it with Mercurial.

Workaround for now: appending `.git` to the end of the url seems to do the trick.

**Comment by pattyjogal** [comment]
If I'm not mistaken, [Bitbucket's spec ](https://confluence.atlassian.com/bitbucket/clone-a-repository-223217891.html) says you need to include the .git on cloning a Bitbucket git repo. So this would make sense.

**Comment by jboynyc** [comment]
Fair enough. But perhaps the error handling could be made more user-friendly. I'll look into providing a patch.
